In [ ]:
import torch

In [ ]:
import re

In [ ]:
import json

In [ ]:
import pickle

In [ ]:
import tqdm

In [ ]:
from dotenv import load_dotenv

In [ ]:
load_dotenv()

False

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
from transformers import AutoProcessor, AutoModelForCausalLM

In [ ]:
MODEL_ID = "google/gemma-4-E2B-it"

In [ ]:
processor = AutoProcessor.from_pretrained(MODEL_ID, temperature=0.1)

In [ ]:
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype="auto", device_map="auto")

Loading weights:   0%|          | 0/1951 [00:00<?, ?it/s]

In [ ]:
df = pd.read_excel("data_clean.xlsx", header=0)

In [ ]:
df.head(10)

,title_rus,title_eng,annotation,description
0,Исследование приоритетов и механизмов реализац...,Study of Priorities and Mechanisms for Impleme...,Работа международных фондов (доноров) должна п...,"Согласно определению международных фондов, про..."
1,Антрополе - научно-популярный видео-подкаст о ...,Anthropole is a Popular Science Video Podcast ...,"\tАнтрополе - научно-популярный проект, в рамк...","Социальное знание близко и интересно обществу,..."
2,"Разработка, создание и ведение сайта, посвящен...","Design, Development and Implementation of a We...",Художественное образование и творчество художн...,Тема обучения арабских художников в художестве...
3,Перевод с английского языка коллективной моног...,Translation from English of the collective mon...,"Коллективная монография, авторы которой являют...","Коллективная монография, авторы которой являют..."
4,Сеть военно-политических союзов в Евразии: баз...,Network of Military in Eurasia: a Database,Проект посвящен изучению сети военно-политичес...,Проект посвящен анализу истории существования ...
5,Дизайн учебных материалов (презентаций),Instructional Materials Design (PPT Presentati...,Участникам проекта предлагается оформить две у...,Необходимо оформить две учебные презентации в ...
6,ОРЗ Изучении практик многоязычного обучения в ...,Studying the Practices of Polylingual Educatio...,Участие в нашем проекте будет интересен для те...,Преподавание родного языка и родной литературы...
7,Привязанность к месту и психосоциальное здоров...,Place attachment and psychosocial health: a me...,Привязанность к месту (place attachment) — это...,Привязанность к месту (place attachment) — сра...
8,Подготовка управленческих решений на корпорати...,Preparation of Managerial Decisions at the Co...,Для осуществления управленческих функций необх...,Сложности подготовки управленческих решений на...
9,"Дизайн лонгрида ""Корея в Москве и Санкт-Петерб...","Design of a Longread ""Korea in Moscow and St. ...",Подготовка привлекательного визуального отобра...,Сейчас завершается финальная часть проекта по ...

In [ ]:
with open("artificial_profiles.json", "r") as f:
    profiles = json.load(f)

In [ ]:
with open("titles_with_tags_dict.pkl", "rb") as f:
    titles_with_tags = pickle.load(f)

In [ ]:
data = []

for title in titles_with_tags:
  for tag in titles_with_tags[title]:
    data.append((title, tag))

titles_df = pd.DataFrame(data=data, columns=["title", "tag"])

In [ ]:
titles_df.head()

                                               title                      tag
0  Исследование приоритетов и механизмов реализац...  international_relations
1  Исследование приоритетов и механизмов реализац...      political_economics
2  Исследование приоритетов и механизмов реализац...          policy_analysis
3  Исследование приоритетов и механизмов реализац...                    BRICS
4  Исследование приоритетов и механизмов реализац...              geopolitics

In [ ]:
results = {}

In [ ]:
BATCH_SIZE = 8
MAX_NEW_TOKENS = 50

for profile, description in tqdm.tqdm(list(profiles.items())):
    SYSTEM_PROMPT = f"""
    You are a {profile}.
    Yours bio: '{description['bio']}'
    Yours tags: '{description['tags']}'
    Evaluate, how much you would like proposed student project based on its title in russian and tags. Rate it on a scale [1, 2, 3, 4, 5], where the higher the better.
    Return stricly JSON.
    For example.
    """
    SYSTEM_PROMPT += """
    Input.
    ```json
    {'title': 'Исследование методов решения задачи линейной регрессии', 'tags': ['machine_learning', 'algorithms']}
    ```
    """
    SYSTEM_PROMPT += """
    Output.
    ```json
    {'score': 5}
    ```
    """

    messages = [
        (
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps({"title": row[1]["title"], "tags": titles_with_tags[row[1]["title"]]}, ensure_ascii=False)},
        )
        for row in titles_df[titles_df["tag"].isin(description["tags"])].iterrows()
    ]

    titles = [msg[1]["content"] for msg in messages]

    scores = {}

    for batch_start in range(0, len(messages), BATCH_SIZE):
        batch = messages[batch_start : batch_start + BATCH_SIZE]

        texts = [
            processor.apply_chat_template(
                msg, tokenize=False, add_generation_prompt=True, enable_thinking=False
            )
            for msg in batch
        ]

        inputs = processor(text=texts, return_tensors="pt", padding=True).to(
            model.device
        )
        input_len = inputs["input_ids"].shape[-1]

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                pad_token_id=processor.tokenizer.pad_token_id,
            )

        responses = processor.batch_decode(
            outputs[:, input_len:], skip_special_tokens=False
        )

        for title, response in zip(
            titles[batch_start : batch_start + BATCH_SIZE], responses
        ):
            try:
                json_match = re.search(r"```json\s*(.*?)\s*```", response, re.DOTALL)
                if json_match:
                    json_str = json_match.group(1)
                else:
                    json_str = response
                answer = json.loads(json_str)
            except Exception:
                answer = {"score": None}

            try:
                score = answer.get("score", None)
                score = int(score)
                scores[title] = score
            except (TypeError, ValueError):
                pass

    values = list(scores.values())
    if len(values):
        median = np.median(values)
    else:
        median = np.nan

    print(f"{profile}: {len(values)}, {median}")
    results[profile] = scores

  3%|▎         | 1/31 [00:54<27:21, 54.72s/it]

global_economics_and_geopolitics_analyst: 195, 4.0

  6%|▋         | 2/31 [01:17<17:17, 35.76s/it]

international_relations_and_geopolitics_expert: 85, 4.0

 10%|▉         | 3/31 [01:39<13:49, 29.62s/it]

multilingual_linguistics_researcher: 115, 5.0

 13%|█▎        | 4/31 [02:06<12:47, 28.43s/it]

education_and_cultural_development_expert: 120, 4.0

 16%|█▌        | 5/31 [02:54<15:30, 35.80s/it]

sociocultural_anthropologist_and_politician: 236, 4.0

 19%|█▉        | 6/31 [03:24<14:00, 33.62s/it]

social_media_and_marketing_strategist: 114, 5.0

 23%|██▎       | 7/31 [04:08<14:46, 36.93s/it]

cultural_humanities_researcher_media_studies: 162, 4.0

 26%|██▌       | 8/31 [04:23<11:32, 30.13s/it]

digital_platform_developer_and_educator: 82, 4.0

 29%|██▉       | 9/31 [04:53<10:59, 29.96s/it]

historical_culture_researcher_media_specialist: 102, 4.0

 32%|███▏      | 10/31 [04:58<07:51, 22.45s/it]

media_and_culture_strategist: 29, 5.0

 35%|███▌      | 11/31 [05:07<06:02, 18.14s/it]

psychological_researcher_and_wellbeing_expert: 39, 5.0

 39%|███▊      | 12/31 [05:35<06:42, 21.20s/it]

literary_and_cultural_analyst_cross_cultural: 125, 4.0

 42%|████▏     | 13/31 [05:59<06:36, 22.02s/it]

legal_policy_and_ethics_researcher: 106, 4.0

 45%|████▌     | 14/31 [06:33<07:14, 25.58s/it]

geopolitics_and_international_relations_expert: 128, 4.0

 48%|████▊     | 15/31 [06:40<05:19, 19.95s/it]

multilingual_nlp_and_ai_specialist: 32, 5.0

 52%|█████▏    | 16/31 [07:00<05:03, 20.23s/it]

political_science_international_relations_analyst: 86, 4.5

 55%|█████▍    | 17/31 [07:09<03:53, 16.66s/it]

educational_psychologist_and_methodologist: 40, 5.0

 58%|█████▊    | 18/31 [07:35<04:14, 19.61s/it]

media_and_communications_specialist: 122, 5.0

 61%|██████▏   | 19/31 [07:47<03:24, 17.08s/it]

financial_economist_and_analyst: 57, 4.0

 65%|██████▍   | 20/31 [08:16<03:48, 20.77s/it]

ai_policy_and_social_impact_analyst: 134, 4.0

 68%|██████▊   | 21/31 [08:34<03:20, 20.02s/it]

ai_and_nlp_developer: 89, 4.0

 71%|███████   | 22/31 [09:02<03:21, 22.37s/it]

strategic_management_consultant_and_leader: 144, 4.0

 74%|███████▍  | 23/31 [09:12<02:28, 18.59s/it]

multidisciplinary_tech_and_language_developer: 53, 5.0

 77%|███████▋  | 24/31 [09:51<02:53, 24.75s/it]

regional_studies_and_geopolitics_expert: 156, 4.0

 81%|████████  | 25/31 [10:16<02:29, 24.87s/it]

data_driven_policy_analyst: 83, 4.0

 84%|████████▍ | 26/31 [10:52<02:21, 28.22s/it]

strategic_consultant_and_market_analyst: 160, 4.0

 87%|████████▋ | 27/31 [11:17<01:49, 27.29s/it]

educational_tech_developer: 101, 5.0

 90%|█████████ | 28/31 [11:39<01:17, 25.78s/it]

media_journalism_and_cultural_studies_expert: 120, 4.0

 94%|█████████▎| 29/31 [12:09<00:53, 26.80s/it]

digital_marketing_and_media_strategy: 116, 5.0

 97%|█████████▋| 30/31 [12:23<00:22, 22.97s/it]

media_and_communication_strategist: 45, 5.0

100%|██████████| 31/31 [13:00<00:00, 25.19s/it]

cultural_and_media_anthropologist: 154, 4.0

In [ ]:
with open("artificial_profiles_scores.pkl", "wb") as f:
    pickle.dump(results, f)