In [1]:
import re

In [2]:
import json

In [3]:
import pickle

In [4]:
import tqdm

In [5]:
from dotenv import load_dotenv

In [6]:
load_dotenv()

False

In [7]:
import pandas as pd

In [8]:
from transformers import AutoProcessor, AutoModelForCausalLM

In [9]:
MODEL_ID = "Qwen/Qwen3-4B-Instruct-2507"

In [10]:
processor = AutoProcessor.from_pretrained(MODEL_ID)

In [11]:
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype="auto", device_map="auto")

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

In [12]:
with open("preds_wo_features.pkl", "rb") as f:
    preds_wo_features = pickle.load(f)

In [13]:
with open("preds_w_features.pkl", "rb") as f:
    preds_w_features = pickle.load(f)

In [14]:
with open("titles_with_tags_dict.pkl", "rb") as f:
    titles_with_tags_dict = pickle.load(f)

In [15]:
with open("artificial_profiles.json", "rb") as f:
    artificial_profiles = json.load(f)

In [16]:
SYSTEM_PROMPT = """
You are a helpful assistant, which can evaluate, wherether or not a proposed project fits student interests, and explain.
Return strictly JSON. Take into account bio and interests of a student.
Example Input:
```
You are machine_learning_researcher student.
Your bio is 'A student, which enjoys solving machine learning problems'.
Your interests are ['machine_learning', deep_learning'].
You are proposed with a project named 'Рекомендательная система студенческих проектов' with corresponding tags ['machine_learning', 'deep_learning', 'recommender_systems'].
```
Exapmle Output:
```json
{'is_valid_recommendation': 1, 'explanation': 'The recommendaditon is valid in terms of semantric relevance and tags intersection'}
```
"""

In [17]:
def process(df):
    messages = []

    for row in df.iterrows():
        user_name = row[1].user_name
        user_bio = artificial_profiles[user_name]["bio"]
        user_tags = artificial_profiles[user_name]["tags"]

        item_title = row[1].item_title
        item_tags = titles_with_tags_dict[item_title]

        USER_MESSAGE = f"""
        You are {user_name} student.
        Your bio is '{user_bio}'.
        Your interests are {user_tags}.
        You are proposed with a project named '{item_title}' with corresponding tags {item_tags}.
        """

        messages.append({
            "user_name": user_name,
            "item_title": item_title,
            "shared_tags": len(set(user_tags).intersection(item_tags)) / len(item_tags),
            "message":
            (
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": USER_MESSAGE},
            ),
            })

    data = []

    for row in tqdm.tqdm(messages):
        text = processor.apply_chat_template(
            row["message"], tokenize=False, add_generation_prompt=True, enable_thinking=False
        )

        inputs = processor(text=text, return_tensors="pt").to(model.device)
        input_len = inputs["input_ids"].shape[-1]

        outputs = model.generate(**inputs, max_new_tokens=1024)
        response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)

        try:
            json_match = re.search(r"```json\s*(.*?)\s*```", response, re.DOTALL)
            if json_match:
                json_str = json_match.group(1)
            else:
                json_str = response
            answer = json.loads(json_str)
        except Exception:
            answer = {"is_valid_recommendation": None}

        try:
            is_valid = answer.get("is_valid_recommendation", None)
            is_valid = int(is_valid)
            explanation = answer.get("explanation", None)
            data.append((row["user_name"], row["item_title"], row["shared_tags"], is_valid, explanation))
        except (TypeError, ValueError):
            pass

    return pd.DataFrame(data=data, columns=["user_name", "item_title", "shared_tags", "is_valid", "explanation"])

In [18]:
preds_wo_features_scores = process(preds_wo_features)

100%|██████████| 310/310 [27:56<00:00,  5.41s/it]

In [19]:
preds_w_features_scores = process(preds_w_features)

100%|██████████| 310/310 [28:16<00:00,  5.47s/it]

In [20]:
preds_wo_features_scores.is_valid.mean()

np.float64(0.8258064516129032)

In [21]:
preds_w_features_scores.is_valid.mean()

np.float64(0.8935483870967742)

In [22]:
pwofg = preds_wo_features_scores.groupby(by=["user_name"]).agg({"is_valid": "mean"}).reset_index(drop=False)
pwofg.columns = ["user_name", "mean_score"]
pwofg = pwofg.sort_values(by=["mean_score"], ascending=False).reset_index(drop=True)

In [23]:
pwofg

                                            user_name  mean_score
0                digital_marketing_and_media_strategy         1.0
1                          data_driven_policy_analyst         1.0
2        cultural_humanities_researcher_media_studies         1.0
3      geopolitics_and_international_relations_expert         1.0
4            global_economics_and_geopolitics_analyst         1.0
5      historical_culture_researcher_media_specialist         1.0
6      international_relations_and_geopolitics_expert         1.0
7   political_science_international_relations_analyst         1.0
8             regional_studies_and_geopolitics_expert         1.0
9          strategic_management_consultant_and_leader         1.0
10              social_media_and_marketing_strategist         1.0
11                 media_and_communication_strategist         1.0
12       media_journalism_and_cultural_studies_expert         1.0
13                media_and_communications_specialist         1.0
14                  cultural_and_media_anthropologist         0.9
15        sociocultural_anthropologist_and_politician         0.9
16      multidisciplinary_tech_and_language_developer         0.9
17                       media_and_culture_strategist         0.9
18       literary_and_cultural_analyst_cross_cultural         0.8
19            strategic_consultant_and_market_analyst         0.8
20                 multilingual_nlp_and_ai_specialist         0.8
21                    financial_economist_and_analyst         0.8
22                 legal_policy_and_ethics_researcher         0.8
23          education_and_cultural_development_expert         0.7
24                               ai_and_nlp_developer         0.7
25                         educational_tech_developer         0.7
26            digital_platform_developer_and_educator         0.6
27         educational_psychologist_and_methodologist         0.6
28                ai_policy_and_social_impact_analyst         0.3
29                multilingual_linguistics_researcher         0.3
30      psychological_researcher_and_wellbeing_expert         0.1

In [24]:
pwfg = preds_w_features_scores.groupby(by=["user_name"]).agg({"is_valid": "mean"}).reset_index(drop=False)
pwfg.columns = ["user_name", "mean_score"]
pwfg = pwfg.sort_values(by=["mean_score"], ascending=False).reset_index(drop=True)

In [25]:
pwfg

                                            user_name  mean_score
0                   cultural_and_media_anthropologist         1.0
1                          data_driven_policy_analyst         1.0
2        cultural_humanities_researcher_media_studies         1.0
3                digital_marketing_and_media_strategy         1.0
4            global_economics_and_geopolitics_analyst         1.0
5      historical_culture_researcher_media_specialist         1.0
6      international_relations_and_geopolitics_expert         1.0
7      geopolitics_and_international_relations_expert         1.0
8   political_science_international_relations_analyst         1.0
9             regional_studies_and_geopolitics_expert         1.0
10                multilingual_linguistics_researcher         1.0
11                       media_and_culture_strategist         1.0
12       media_journalism_and_cultural_studies_expert         1.0
13                 media_and_communication_strategist         1.0
14                media_and_communications_specialist         1.0
15            strategic_consultant_and_market_analyst         1.0
16        sociocultural_anthropologist_and_politician         1.0
17              social_media_and_marketing_strategist         1.0
18                 multilingual_nlp_and_ai_specialist         1.0
19         strategic_management_consultant_and_leader         0.9
20      multidisciplinary_tech_and_language_developer         0.9
21                         educational_tech_developer         0.9
22       literary_and_cultural_analyst_cross_cultural         0.9
23                ai_policy_and_social_impact_analyst         0.8
24                               ai_and_nlp_developer         0.8
25                    financial_economist_and_analyst         0.8
26            digital_platform_developer_and_educator         0.8
27                 legal_policy_and_ethics_researcher         0.7
28          education_and_cultural_development_expert         0.7
29         educational_psychologist_and_methodologist         0.4
30      psychological_researcher_and_wellbeing_expert         0.1

In [26]:
for explanation in preds_wo_features_scores.head(8).explanation.to_list():
  print(explanation)

The recommendation is valid in terms of semantic relevance and tags intersection. The project 'Цифровой универсальный комментарий' aligns with the student's interests in NLP, computer linguistics, and software engineering, all of which are directly covered in their interests and bio.
The project 'Учебный ассистент по курсу "Бухгалтерский учет"' aligns well with the student's interests in AI, NLP, and educational technology. The tags include 'ai' and 'educational_technology', which are directly relevant to the student's focus on intelligent systems and adaptive learning platforms. Additionally, the project involves a student assistant, which connects to their interest in chatbots and AI design. Although 'accounting' is a specific domain, the integration of AI and NLP in an educational context fits within the student's broader expertise and interests.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in NLP, machine learning, programming language, and educational technology align well with the project's focus on a multi-agent intelligent learning system for JavaScript. The tags 'machine_learning', 'programming_language', and 'educational_technology' are directly relevant to the student's interests and bio, making this a strong fit.
The recommendation is valid in terms of semantic relevance and tags intersection. The project involves natural language processing, chatbot development, and machine learning, all of which align with the student's interests in NLP, chatbots, and machine learning. Additionally, the project's focus on software development and language technology fits within the student's broader profile in AI and NLP applications.
The project is highly relevant to the student's interests in NLP, machine learning, and AI-based tools. The tags include natural_language_processing, text_summarization, and artificial_intelligence, which align well with the student's bio and interests in building intelligent systems like chatbots and language processing tools. The project also touches on speech recognition and language learning, which are consistent with their focus on language technology and real-world applications in education.
The project involves generative AI and scriptwriting, which aligns well with the student's interests in NLP, large language models, and AI-driven content creation. The tags 'generative_ai', 'scriptwriting', and 'storyboarding' are semantically relevant to the student's background in NLP and AI design, and the project's focus on pre-production content generation fits within their interest in AI applications in education and content creation.
The project focuses on mobile development, computer vision, and urban planning, which have limited overlap with the student's interests in NLP, large language models, chatbots, and text analysis. Although AI is a common tag, the specific focus on computer vision and urban planning does not align well with the student's strengths and interests in NLP and dialogue systems.
The project 'LegalConnect: Интерактивная образовательная платформа для студентов-юристов' aligns well with the student's interests in educational technology, software development, and AI-driven platforms. Although the tags do not explicitly include NLP or large language models, the focus on an interactive educational platform for law students suggests potential integration of NLP-based tools (e.g., chatbots, text analysis) and AI design, which are within the student's expertise and interests. The overlap in software development and educational technology makes the project semantically relevant and feasible for the student's skill set.

In [27]:
for explanation in preds_wo_features_scores.tail(8).explanation.to_list():
  print(explanation)

The project is valid in terms of semantic relevance and tags intersection. The student's interests in market analysis, economics, and data analysis align well with the project's focus on market research in the food industry. Additionally, the student's expertise in strategic management and business strategy supports a thorough analysis of market dynamics, making this a relevant and suitable project.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in strategic management, corporate strategy, data analysis, and AI align with the economic and financial analysis aspects of the project, particularly in the context of monetary policy and central banking. Although the focus is on macroeconomics, the student's background in strategic and data-driven decision-making supports a strong analytical approach to the topic.
The project is valid in terms of semantic relevance and tags intersection. The proposed project on EAEU integration from a trade perspective aligns with the student's interests in international business, international economics, and economic integration. The tags 'economics', 'trade', 'integration', and 'international_economics' are directly connected to the student's interests in international business and economic strategy, making it a relevant and suitable match.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in strategic management, international business, and digital marketing align well with the project's focus on international marketing and digital promotion. Additionally, the student's expertise in data analysis and AI can be leveraged for targeted marketing strategies, and the geopolitical context of China and BRICS adds strategic depth to the project.
The project is valid in terms of semantic relevance and tags intersection. The proposed project involves business strategy and marketing, which align with the student's interests in business_strategy, strategic_management, and management. Although the focus is on hospitality and service management, it still falls within the broader domain of business and strategic decision-making, supported by the student's expertise in corporate strategy and data analysis.
The project is valid in terms of semantic relevance and tags intersection. The proposed project on promoting Russian brands in the Chinese market aligns with the student's interests in international business, business strategy, and cross-cultural marketing. The tags 'international_marketing', 'brand_management', and 'business_strategy' are directly relevant to the student's expertise and interests, especially given their focus on geopolitical strategy and market analysis.
The project is valid in terms of semantic relevance and tags intersection, as it aligns with the student's interests in project management and strategic leadership. Although the focus is on entrepreneurship and marketing, the presence of project management and team building connects well with the student's expertise in project management and organizational transformation.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in economics, macroeconomics, data analysis, and AI align well with the project's focus on inflation, econometrics, and time series analysis. Given the student's background in strategic management and international business, understanding macroeconomic factors like inflation is directly relevant to corporate strategy and global economic decision-making.

In [28]:
for explanation in preds_w_features_scores.head(8).explanation.to_list():
  print(explanation)

The project 'Цифровой универсальный комментарий' aligns well with the student's interests in NLP, natural language processing, and software engineering. The tags 'natural_language_processing', 'nlp', and 'computer_linguistics' directly match the student's interests, and the involvement of software engineering fits their background in platform development and programming. The project is semantically relevant and intersects with the student's expertise and passions.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in NLP, machine learning, programming language, and educational technology align well with the project's focus on a multi-agent intelligent learning system for JavaScript. The tags 'machine_learning', 'programming_language', and 'educational_technology' are directly relevant to the student's bio and interests, especially given their interest in adaptive learning platforms and dialogue systems.
The project 'Учебный ассистент по курсу "Бухгалтерский учет"' aligns well with the student's interests in AI, NLP, and educational technology. The tags include 'ai' and 'educational_technology', which are directly relevant to the student's focus on intelligent systems and adaptive learning platforms. Additionally, the project involves building a student assistant, which connects to their interest in chatbots and AI design. Although 'accounting' is specific, the integration of NLP and AI for educational support fits within their broader skill and interest profile.
The project aligns well with the student's interests in NLP, chatbots, and machine learning. The tags 'natural_language_processing', 'chatbot', and 'machine_learning' are directly relevant to the student's interests. Additionally, the project involves software development, which is also within the student's skill and interest scope. Although 'bioinformatics' is a less familiar domain, it is not outside the student's capabilities given their interest in AI and language processing applied to real-world problems. Overall, the semantic relevance and tag intersection make this a valid recommendation.
The project is valid in terms of semantic relevance and tags intersection. The proposed project involves machine learning and AI, which align with the student's interests in NLP, machine learning, and AI design. Additionally, the focus on educational technology (edtech) and personalization ties into the student's interest in adaptive learning platforms and real-world applications in education. The tags 'machine_learning', 'ai', and 'software_engineering' are directly aligned with the student's bio and interests.
The project is highly relevant to the student's interests in NLP, machine learning, and AI-driven tools. The tags include natural_language_processing, text_summarization, and artificial_intelligence, which align directly with the student's bio and interests in building intelligent systems like chatbots and language processing tools. The project also involves speech recognition and language learning, which extend their interest in language technology and real-world applications in education.
The recommendation is valid in terms of semantic relevance and tags intersection. The project 'Мастер-класс по автоматизированной обработке текстовых данных' aligns well with the student's interests in NLP, text analysis, and data processing, all of which are explicitly mentioned in their interests and bio.
The project involves AI and NLP elements such as a Telegram bot and AI-driven content, which aligns with the student's interests in NLP, machine learning, and AI design. The focus on self-development and health, combined with AI integration, fits well with their interest in real-world applications of AI and language technology. Although mobile development is included, it is not a primary focus, and the student's strong background in NLP and AI makes the project semantically relevant and technically feasible.

In [29]:
for explanation in preds_w_features_scores.tail(8).explanation.to_list():
  print(explanation)

The project is valid in terms of semantic relevance and tags intersection. The proposed project focuses on international business strategy and brand management in a global market (China), which aligns well with the student's interests in strategic management, business strategy, international business, and cross-cultural marketing. The tags 'business_strategy' and 'international_marketing' are directly relevant to the student's expertise and interests.
The project is valid in terms of semantic relevance and tags intersection. The proposed project involves business strategy and communication strategy, which align with the student's interests in business_strategy, strategic_management, and management. Although the focus is on regional marketing, it falls within the broader scope of business strategy and organizational communication, supported by the student's expertise in corporate strategy and data analysis.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in market analysis, economics, and data analysis align well with the project's focus on market research in the food industry. Additionally, the student's background in strategic management and business strategy supports an analytical approach to the project.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in market analysis, data analysis, and economics align well with the project's focus on market structure and financial technology. Additionally, the use of data mining and market analysis fits within the student's expertise in strategic management and business strategy.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in economics, financial policy, and geopolitical strategy (including Russia) align well with the project's focus on monetary policy and Russia's economic context. Additionally, the student's expertise in data analysis and AI can be applied to model and analyze economic trends, enhancing the project's analytical depth.
The project is valid in terms of semantic relevance and tags intersection. The student's interests in strategic management, business strategy, economics, data analysis, and AI align well with the project's focus on financial innovation and monetary policy in Russia. Additionally, the student's expertise in macroeconomics and geopolitical strategy supports an analysis of Russia's financial context, making the project a relevant and suitable fit.
The project is semantically relevant as it falls within the domain of economics and monetary policy, which aligns with the student's interests in strategic management, business strategy, data analysis, and AI-driven decision-making. The tags intersect with the student's expertise in economic analysis and organizational transformation, especially when considering AI applications in financial and macroeconomic decision-making.
The project topic focuses on monetary policy in Russia, which falls under economics and finance. While the student has interests in data analysis and AI, and has a background in strategic management and geopolitical strategy, the project does not align closely with their core interests in strategic management, international business, or corporate strategy. The tags do not intersect significantly with the student's interests, and there is limited connection to AI or organizational transformation. Therefore, the recommendation is not valid in terms of semantic relevance and interest alignment.

In [30]:
with open("preds_wo_features_scores.pkl", "wb") as f:
  pickle.dump(preds_wo_features_scores, f)

In [31]:
with open("preds_w_features_scores.pkl", "wb") as f:
  pickle.dump(preds_w_features_scores, f)

In [ ]:
SYSTEM_PROMPT = """
You are a helpful assistant, summarize information related to project recommendations fit between to algorithms. Say, which one is better and explain in details.
Your input:
```[{'algo_name': 'lightfm_without_features', 'data': {'overall_accuracy': 0.5, 'eplanations': ['the recommendation is good', 'the recommendations is bad']}}, {'algo_name': 'lightfm_with_features', 'data': {'overall_accuracy': 1.0, 'eplanations': ['the recommendation is excellent', 'the recommendations is good']}}]```
Your output:
```'lightfm_with_features' better in terms of overall accuracy, semantic relevance and tags fit```
"""

In [38]:
USER_MESSAGE = json.dumps([
    {"algo_name": "lightfm_without_features", "overall_accuracy": preds_wo_features_scores.is_valid.mean(), "explanations": preds_wo_features_scores.explanation.to_list()},
    {"algo_name": "lightfm_with_features", "overall_accuracy": preds_w_features_scores.is_valid.mean(), "explanations": preds_w_features_scores.explanation.to_list()},
], ensure_ascii=False)

message = (
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_MESSAGE},
    )

text = processor.apply_chat_template(
    message, tokenize=False, add_generation_prompt=True, enable_thinking=False
)

inputs = processor(text=text, return_tensors="pt").to(model.device)
input_len = inputs["input_ids"].shape[-1]

outputs = model.generate(**inputs, max_new_tokens=1024)
response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)

In [39]:
print(response)

`lightfm_with_features` is better in terms of overall accuracy, semantic relevance, and tags fit.

### Detailed Explanation:

1. **Overall Accuracy**:
   - `lightfm_with_features` achieves an **overall accuracy of 0.8935**, which is **higher** than `lightfm_without_features` (0.8258).
   - This indicates that the algorithm with feature integration performs better in predicting relevant project recommendations, resulting in fewer mismatches and more accurate alignment with the student's profile.
   - The improved accuracy reflects a more robust understanding of the student’s interests, as features (such as tags, domain-specific keywords, and thematic overlap) enhance the model’s ability to capture nuanced preferences.

2. **Semantic Relevance**:
   - The explanations for `lightfm_with_features` consistently emphasize **strong semantic alignment** between the recommended projects and the student’s stated interests.
   - Projects are described as aligning with core areas such as:
     - **Natural Language Processing (NLP)** and **machine learning** (e.g., "aligns with the student's interests in NLP, machine learning, and AI design").
     - **Education technology (edtech)** and **chatbot development** (e.g., "the project involves chatbot development using NLP").
     - **Cultural studies, media, and cross-cultural communication** (e.g., "aligns well with the student's interests in cultural studies, media studies, and cross-cultural communication").
   - In contrast, `lightfm_without_features` shows **more generic or surface-level relevance**, with explanations that lack depth in connecting specific project domains to the student’s interests.
   - For instance, some recommendations in `lightfm_without_features` mention only general terms like "valid in terms of semantic relevance" without detailing how the project’s content, tags, or domain directly match the student’s profile.

3. **Tags Fit**:
   - `lightfm_with_features` explicitly references **specific tags** that match the student’s interests (e.g., `nlp`, `education_technology`, `machine_learning`, `cultural_studies`, `international_relations`).
   - These tags are not only present but are **contextually justified**—e.g., "the project involves machine learning and AI, which align with the student's interests in NLP and AI design."
   - In contrast, `lightfm_without_features` often lacks such explicit tag-to-interest mapping, relying on vague statements like "the recommendation is good" or "valid in terms of semantic relevance" without specifying which tags or domains are relevant.

4. **Domain Coverage and Interdisciplinary Fit**:
   - `lightfm_with_features` recommends projects that span multiple domains—such as **AI in education**, **cultural studies**, **geopolitics**, and **language technology**—all of which are explicitly mentioned in the student’s interests.
   - This demonstrates a more **holistic and interdisciplinary understanding** of the student’s profile.
   - The algorithm effectively identifies projects that combine technical components (e.g., NLP, machine learning) with real-world applications (e.g., chatbots, educational tools), which aligns with the student’s background in software engineering, AI, and education technology.

5. **Avoidance of Misalignment**:
   - `lightfm_with_features` avoids recommending projects with weak or irrelevant connections (e.g., computer vision, signal processing, or unrelated domains like ancient geography).
   - In contrast, `lightfm_without_features` includes some recommendations that are only marginally relevant, such as "the project focuses on mobile development, computer vision, and urban planning," which has limited overlap with the student’s core interests in NLP and AI.

---

### Conclusion:
`lightfm_with_features` outperforms `lightfm_without_features` due to its **superior accuracy, deeper semantic relevance, and precise tag alignment** with the student’s interests. By incorporating features such as project tags, domain-specific keywords, and thematic content, the algorithm provides more meaningful, contextually grounded, and personalized recommendations. This makes it the clearly better choice for project recommendation in this context.<|im_end|>