In [1]:
import pickle

In [2]:
import pandas as pd

In [3]:
with open("preds_wo_features_scores.pkl", "rb") as f:
    preds_wo_features_scores = pickle.load(f)

In [4]:
preds_wo_features_scores.head()

,user_name,item_title,is_valid
0,ai_and_nlp_developer,Цифровой универсальный комментарий,1
1,ai_and_nlp_developer,"Учебный ассистент по курсу "" Бухгалтерский учет""",1
2,ai_and_nlp_developer,Мультиагентная интеллектуальная обучающая сист...,1
3,ai_and_nlp_developer,Разработка чат-бота для выбора пептидов для се...,1
4,ai_and_nlp_developer,Интеллектуальный помощник по обработке лекций ...,1

In [5]:
with open("preds_w_features_scores.pkl", "rb") as f:
    preds_w_features_scores = pickle.load(f)

In [6]:
preds_w_features_scores.head()

,user_name,item_title,is_valid
0,ai_and_nlp_developer,Цифровой универсальный комментарий,1
1,ai_and_nlp_developer,Мультиагентная интеллектуальная обучающая сист...,1
2,ai_and_nlp_developer,"Учебный ассистент по курсу "" Бухгалтерский учет""",1
3,ai_and_nlp_developer,Разработка чат-бота для выбора пептидов для се...,1
4,ai_and_nlp_developer,Разработка MVP платформы для ИИ-персонализации...,1

In [7]:
pwofg = (
    preds_wo_features_scores.groupby(by=["user_name"])
    .agg({"is_valid": "mean"})
    .reset_index(drop=False)
)
pwofg.columns = ["user_name", "mean_score"]
pwofg = pwofg.sort_values(by=["mean_score"], ascending=False).reset_index(drop=True)

In [8]:
pwofg.head()

                                        user_name  mean_score
0      strategic_management_consultant_and_leader         1.0
1         regional_studies_and_geopolitics_expert         1.0
2             media_and_communications_specialist         1.0
3              media_and_communication_strategist         1.0
4  international_relations_and_geopolitics_expert         1.0

In [9]:
pwfg = (
    preds_w_features_scores.groupby(by=["user_name"])
    .agg({"is_valid": "mean"})
    .reset_index(drop=False)
)
pwfg.columns = ["user_name", "mean_score"]
pwfg = pwfg.sort_values(by=["mean_score"], ascending=False).reset_index(drop=True)

In [10]:
pwfg.head()

                                        user_name  mean_score
0      strategic_management_consultant_and_leader         1.0
1  geopolitics_and_international_relations_expert         1.0
2             multilingual_linguistics_researcher         1.0
3    media_journalism_and_cultural_studies_expert         1.0
4                    media_and_culture_strategist         1.0

In [11]:
final = pwofg.merge(pwfg, on=["user_name"])
final["diff"] = final["mean_score_y"] - final["mean_score_x"]

In [12]:
final.to_excel("llm_as_a_judge.xlsx", index=False)