In [1]:
import tqdm

In [2]:
import re

In [3]:
import json

In [4]:
import pickle

In [5]:
from dotenv import load_dotenv

In [6]:
load_dotenv()

True

In [7]:
import pandas as pd

In [8]:
from transformers import AutoProcessor, AutoModelForCausalLM

In [9]:
MODEL_ID = "google/gemma-4-E2B-it"

In [10]:
processor = AutoProcessor.from_pretrained(MODEL_ID)

In [11]:
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, dtype="auto", device_map="auto")

Loading weights:   0%|          | 0/1951 [00:00<?, ?it/s]

In [12]:
with open("titles_with_tags_dict.pkl", "rb") as f:
    titles_with_tags = pickle.load(f)

In [13]:
len(titles_with_tags)

1187

In [14]:
data = []

In [15]:
for title, tags in titles_with_tags.items():
    for tag in tags:
        data.append((title, tag))

In [16]:
data[0]

('Исследование приоритетов и механизмов реализации отраслевых (секторальных) политик в избранных странах БРИКС (членах и кандидатах), во взаимосвязи с повесткой международных доноров',
 'international_relations')

In [17]:
data[-1]

('Обзор Методологии в Области Регионоведения. Этап сбора данных 1.',
 'regional_studies')

In [18]:
df = pd.DataFrame(data=data, columns=["title_rus", "tag"])

In [19]:
df

,title_rus,tag
0,Исследование приоритетов и механизмов реализац...,international_relations
1,Исследование приоритетов и механизмов реализац...,political_economics
2,Исследование приоритетов и механизмов реализац...,policy_analysis
3,Исследование приоритетов и механизмов реализац...,geopolitics
4,Исследование приоритетов и механизмов реализац...,BRICS
...,...,...
6035,Актив Центра развития карьеры - профориентацио...,student_services
6036,Обзор Методологии в Области Регионоведения. Эт...,geography
6037,Обзор Методологии в Области Регионоведения. Эт...,methodology
6038,Обзор Методологии в Области Регионоведения. Эт...,data_collection
6039,Обзор Методологии в Области Регионоведения. Эт...,regional_studies

In [20]:
dfgr = df.groupby(by=["tag"]).agg({"title_rus": "nunique"}).reset_index()
dfgr.columns = ["tag", "count"]
dfgr = dfgr.sort_values(by=["count"], ascending=False).reset_index(drop=True)
dfgr.head(32)

                            tag  count
0       international_relations     97
1                     sociology     96
2                     economics     93
3                   linguistics     92
4          software_engineering     89
5                     marketing     85
6              cultural_studies     76
7                     education     74
8                       history     73
9                 media_studies     70
10                          law     65
11                   psychology     61
12                  geopolitics     59
13                   literature     57
14  natural_language_processing     57
15                      finance     44
16             machine_learning     43
17            political_science     42
18                     pedagogy     41
19           project_management     41
20       educational_technology     40
21                communication     40
22                   management     40
23         software_development     38
24                data_analysis     37
25      artificial_intelligence     36
26             regional_studies     35
27            business_strategy     35
28                      culture     31
29            digital_marketing     30
30                   journalism     27
31              web_development     27

In [21]:
selected_tags = dfgr.head(50)["tag"].to_list()

In [22]:
SYSTEM_PROMPT = """
You are a helpful assistant, which can create artificial user profiles based on student project titles in russian.
Please, analyze given list of student project titles in russian and create several possible user profiles (up to 4) with own preferences in provided field of science.
Return stricly JSON output. Be brief.
For example.
Input data:
```json
{"machine_learning": ["Исследование методов решения задачи линейной регрессии", "Исследование методов решения задачи линейной классификации", "Исследование методов решения задачи обучения с подкреплением"]}
```
Your output:
```json
{"machine_learning_researcher_classic_algorithms": "A user, which is interested in machine learning and classic algorithms in particular", "machine_learning_researcher_reinforcement_learning": "A user, which is interested in machine learning and reinforcement learning in particular"}
```
"""

In [23]:
messages = []

In [24]:
for tag in selected_tags:
    messages.append(
        (
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": json.dumps(
                    {tag: list(df[df["tag"] == tag]["title_rus"].unique())},
                    ensure_ascii=False,
                ),
            },
        )
    )

In [25]:
messages[0][1]["content"]

'{"international_relations": ["Исследование приоритетов и механизмов реализации отраслевых (секторальных) политик в избранных странах БРИКС (членах и кандидатах), во взаимосвязи с повесткой международных доноров", "Сеть военно-политических союзов в Евразии: база данных", "Запуск регулярного подкаста НИУ ВШЭ о странах Азии", "Студенческий клуб \\"Говорим об Эфиопии\\"", "Визовое сопровождение иностранных студентов", "Международный мониторинг ответственного бизнеса", "Школа будущего международника: десятый сезон (2025/2026)", "Внешняя политика России в отношении стран Латинской Америки в XXI веке", "Ближневосточный клуб НИУ ВШЭ: платформа для изучения региона и развития академического и карьерного потенциала студентов-ближневосточников 2025/26", "Японский клуб «Мусуби» НИУ ВШЭ", "Практикум Совета молодых дипломатов", "Новости Ибероамерики-II", "Итальянский клуб ВШЭ", "Исследование правового обеспечения информационной безопасности стран БРИКС", "VII Международная конференция «Мировое большинство»", "Россия и Совет сотрудничества арабских государств Персидского залива (ССАГПЗ): оценка современного состояния взаимодействия и перспектив его развития", "Россия и Организация исламского сотрудничества (ОИС): оценка современного состояния взаимодействия и перспектив развития", "Международные практики поддержки коренных народов Севера", "Развитие российско-китайского сотрудничества: стратегические интересы и экономические практики", "Официальная помощь развитию как инструмент внешней политики Японии", "Африканский семинар", "Китайский клуб НИУ ВШЭ – Санкт-Петербург", "Индийский клуб НИУ ВШЭ – Санкт-Петербург", "Вьетнамский клуб", "Улучшение имиджа Санкт-Петербурга как туристического направления у японской аудитории", "Японский клуб", "Дискуссионно-аналитический клуб по международным отношениям в Восточной Азии", "Ведение социальных сетей кафедры международных отношений и политических процессов стран Азии и Африки", "Подкасты по актуальным вопросам Азии и Африки", "Политический анализ стран Азии и Африки", "Помощь детям из Азии и Ближнего Востока: волонтерская инициатива Российского Красного Креста", "«Тройка» Северо-Восточной Азии: состояние, проблемы и перспективы сотрудничества Китая, Японии и Южной Кореи.", "Журналы \\"Советский Союз\\" (1930-1991) и \\"Советская женщина\\" (1945-1991): мягкая сила и медиа в создании международного имиджа СССР.", "Феномен коллективного Запада и перспективы трансатлантических отношений", "ОРГСЕКТОР: Организация Модели ООН НИУ ВШЭ “HSEMUN-26”", "КОМИТЕТЫ: Работа с комитетами Модели ООН НИУ ВШЭ «HSEMUN-26»", "Арктическая политика неарктических государств: интересы и приоритеты. Часть 2.", "Влияние США, Турции, европейских и ближневосточных государств на энергетические отношения России и Китая со странами Центральной Азии.", "Информационное и организационное сопровождение международной конференции «Россия и Большое Средиземноморье 2025: вызовы, выбор(ы) и возможности»", "Подготовка к конкурсу BRICS Lex (2025)", "Универсальные ценности в цифровом многополярном мире: международный и национальный контур", "Международный дискуссионный клуб кино", "Ассистенты Управления по международным связям", "Государственный суверенитет в условиях глобальных вызовов", "Международные подходы и модели подготовки кадров социально-гуманитарного профиля для традиционных и коммерческих космических программ", "МЕДИАСЕКТОР Сопровождение Модели ООН НИУ ВШЭ “HSEMUN-26”: Дизайнеры", "МЕДИАСЕКТОР Сопровождение Модели ООН НИУ ВШЭ “HSEMUN-26”: SMM и фото/видеосопровождение", "Российская Федерация и страны Европы: история отношений", "Российская Федерация и страны Северной Африки и Среднего Востока", "Сопровождение стратегической проектной деятельности Института мировой военной экономики и стратегии ФМЭиМП", "Российская Федерация и страны Латинской Америки: история отношений ", "«ISU Buddy» – программа адаптационного сопровождения иностранных студентов (2025/2026 г.)", "Россия и ваша страна: Центральная Азия", "Российская Федерация и страны Азии: история отношений", "Инструментарий исследования меэждународных отношений", "Россия и ваша страна: Европа, Азия, Африка", "Российско-белорусские отношения (2022-2025)", "Российско-украинский конфликт (2022-2025)", "Антикоррупционная молодежная политика в странах БРИКС: социологические и психологические факторы в меняющемся мире", "Стратагемность во внутренней и внешней политике Китая", "Российская Федерация и страны Субсахарской Африки: история отношений", "Комплексное исследование международных климатических объединений", "Анализ изменения режимов экспортного контроля западных стран", "Международный конкурс «Разрешение споров в ЕАЭС–2025»: подготовка и участие команды факультета права", "Цифровая дипломатия в эпоху ИИ: этика, право и будущее международных отношений. (Григорьева, Газарян, Слащева)", "Влияние США, европейских и ближневосточных государств и Турции на энергетические отношения Китая и России со странами Центральной Азии.", "Подготовка контрольно-измерительных материалов для интеллектуальных конкурсов по международным отношениям", "Менторский проект конкурса \\"Высший пилотаж\\" по направлению \\"Международные отношения\\"", "Россия и ваша страна : Центральная Азия ", "Россия и Ваша страна: Центральная Азия ", "Амбассадор научного сотрудничества для Института образования", "Сравнительный межстрановой анализ макроуровневых нарративов", "Формирование государственной политики Китая по достижению технологического суверенитета в ответ на санкции США", "Эволюция Военной Позиции Японии в 1989 - 2025", "Вольная редакция ОП «Политология и мировая политика»", "Проект Network for Asia Vision Initiative (NAVI)", "Подготовка и проведение Восьмой международной конференции Модели ООН «Higher School of Economics International Model United Nations» – HSEIMUN 2026", "Совершенствование механизмов государственной социальной поддержки студентов: опыт стран БРИКС", "Международные амбассадоры НИУ ВШЭ – Санкт-Петербург", "Медиацентр Дирекции по работе с молодёжью за рубежом", "Особенности политики Королевства Саудовская Аравия в отношении Исламской Республики Ирана в 2010-2025 гг.", "Трансформация российско-китайского сотрудничества в сфере логистической инфраструктуры Дальнего Востока России в 2015–2024 гг.", "Возможности и ограничения стратегического планирования Евразийской интеграции в условиях внешней неопределенности", "«Международные экономические отношения Ирана и России: международно-правовой аспект»", "Особенности газовой дипломатии Российской Федерации в Центральной Азии в 2022-2025 гг.", "Перспективы взаимоотношений России и европейских стран в 2025-2035 гг.", "Роль БРИКС в энергетическом переходе: возможности и вызовы", "Россия и страны Южной, Восточной и Юго-Восточной Азии: история отношений", "Критика Западного универсализма и инструментализация прав женщин в политике интервенций.", "Роль БРИКС в переориентации внешней политики России на глобальный Юг после 2014 года: динамика, инструменты и ограничения", "Особенности экономического сотрудничества Пакистана и Китая (2000-2020)", "\\"Политика Европейского Союза в области прав человека: сравнительный анализ внутреннего принуждения и внешней обусловленности в Венгрии и Грузии\\t\\"", "Роль журналиста в реализации информационной политики ООН", "Эволюция политических отношений между Пакистаном и Ираном после 1979 года", "Научно-исследовательский семинар \\"Теория и практика международных и региональных исследований\\"", "Подготовка к Олимпиаде по истории государства и права России и зарубежных стран", "Влияние Индо-Тихоокеанской стратегии США на Вьетнам в период 2020–2025 гг."]}'

In [26]:
len(messages[0][1]["content"])

7586

In [27]:
answers = {}

In [28]:
for tag, message in tqdm.tqdm(list(zip(selected_tags, messages))):
    try:
        text = processor.apply_chat_template(
            message, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )

        inputs = processor(text=text, return_tensors="pt").to(model.device)
        input_len = inputs["input_ids"].shape[-1]

        outputs = model.generate(**inputs, max_new_tokens=2048)
        response = processor.decode(outputs[0][input_len:], skip_special_tokens=False)

        json_match = re.search(r"```json\s*(.*?)\s*```", response, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            json_str = response

        print(json_str)
        answers.update(json.loads(json_str))
    except Exception as e:
        print(f"something went wrong with tag {tag} - {e}")

  2%|▏         | 1/50 [00:28<23:06, 28.29s/it]

{
  "international_relations_geopolitics_expert": "A user deeply interested in complex geopolitical dynamics, focusing on BRICS, Eurasia, China-Russia relations, energy politics, and regional conflicts (Middle East, Central Asia). Prefers research into strategic interests and policy mechanisms.",
  "international_relations_regional_studies_enthusiast": "A user focused on regional studies, particularly East Asia (Japan, Korea, China, Vietnam) and South Asia. Interested in cultural exchange, specific bilateral relationships, and regional blocs (like the 'Trio' of Northeast Asia).",
  "international_relations_law_and_security_analyst": "A user interested in the legal and security aspects of international relations, including information security, dispute resolution mechanisms (EAEU), and the role of international law in digital diplomacy.",
  "international_relations_student_and_ambassador": "A student or young professional actively involved in student clubs, networking, media management (social media, podcasts), and visa/adaptation support for international students."
}

  4%|▍         | 2/50 [00:54<21:26, 26.80s/it]

{"sociology_culture_and_identity_expert": "A user deeply interested in cultural studies, identity formation, social memory, and the intersection of culture, politics, and media. Prefers qualitative research, ethnography, and critical analysis of cultural phenomena.", "intercultural_communication_and_global_studies": "A user focused on cross-cultural communication, international relations, and comparative studies (e.g., Russia/Mexico, various Asian codes). Interested in global trends, political sociology, and comparative cultural practices.", "social_and_political_theory_researcher": "A user leaning towards theoretical sociology, focusing on large-scale societal structures, political elites, social inequality, and the impact of technology (AI) on society. Seeks high-level theoretical understanding.", "social_and_youth_issues_specialist": "A user interested in contemporary social issues, including youth agency, mental health (e.g., HIV, bullying), social entrepreneurship, and digital culture (memes). Interested in applied sociology and intervention strategies."}

  6%|▌         | 3/50 [01:19<20:25, 26.07s/it]

{
  "macroeconomic_and_geopolitical_analyst": "A user highly interested in global economics, geopolitics, international trade, and macroeconomic trends. Prefers quantitative analysis of large-scale data (e.g., GlobBaro HSE, BRICS, sanctions impact).",
  "russian_economic_policy_expert": "A user focused on the internal economic dynamics of Russia, including monetary policy (inflation, exchange rates, central banking), fiscal policy, regional economics, and the impact of geopolitical turbulence on the national economy.",
  "international_business_and_trade_specialist": "A user interested in comparative economics, international trade relations (Asia, BRICS, ASEAN), foreign investment, and the business environment in different countries (especially emerging markets).",
  "applied_economics_and_fintech_practitioner": "A user interested in practical business applications of economics, including pricing strategy, market analysis (e.g., marketplaces like Ozon), financial innovation, and behavioral economics."
}

  8%|▊         | 4/50 [01:44<19:48, 25.83s/it]

{"linguistics_translator_and_corpus_builder": "A user deeply engaged in language translation, corpus creation, and textual analysis across diverse languages (Japanese, Arabic, Hebrew, Hindi, etc.). Interested in both classical texts and modern media, with a strong focus on linguistic documentation and methodology.", "cross_cultural_communicator_specialist": "A user focused on inter-cultural communication, cross-cultural studies (Russia/Mexico, general), and developing intercultural competence materials. Interested in sociolinguistics and practical communication skills.", "language_curriculum_developer": "A user focused on educational linguistics, curriculum design, and developing teaching materials for various languages (Japanese, Chinese, Korean, French, English). Interested in pedagogical methods and language teaching.", "computational_linguistics_and_NLP_enthusiast": "A user interested in applying computational methods (LLMs, parsers, automatic classification) to linguistic data, morphology, semantics, and dialectology. Interested in the intersection of NLP and language research."}

 10%|█         | 5/50 [02:08<18:55, 25.24s/it]

{
  "education_tech_developer": "A user highly interested in educational technology, software engineering for learning platforms, AI integration in education, and developing various types of assistants (chatbots, learning systems).",
  "full_stack_mobile_developer": "A user focusing on building cross-platform mobile applications (Flutter, React Native, Kotlin) and backend systems (Java, Rust) for various purposes (finance, fitness, social networks).",
  "data_and_system_architect": "A user interested in large-scale data management, database development (including specific domains like economics or legal), system architecture for complex processes (e.g., oil/gas supervision), and data quality monitoring (LLMOps).",
  "media_and_community_builder": "A user interested in content creation, media platforms (Telegram bots, online journals), community building (BuddyUP), and developing interactive media solutions (VR, maps, educational content creation)."
}

 12%|█▏        | 6/50 [02:30<17:36, 24.01s/it]

{
  "digital_marketing_strategist": "A user highly focused on comprehensive digital marketing strategy, encompassing SMM, content creation, brand positioning, and cross-platform promotion across various sectors (education, consumer goods, tech).",
  "brand_management_and_rebranding_expert": "A user with a strong interest in brand strategy, rebranding, product development (FMCG, fashion, beverages), and leveraging personality/AI in marketing communications.",
  "media_and_PR_specialist": "A user focused on media relations, PR campaigns, event promotion, media management for institutions, and strategic communication for cultural or sports entities.",
  "market_research_and_consumer_insights": "A user interested in market analysis, consumer behavior research (especially in niche areas like food, finance, and specific demographics), and identifying market opportunities for new products/services."
}

 14%|█▍        | 7/50 [02:57<17:51, 24.92s/it]

{
  "cultural_studies_media_strategist": "A user deeply interested in cultural studies, media production, and digital presence. Prefers projects involving website development, media promotion, content strategy for cultural programs, and analyzing the impact of media on cultural spheres (e.g., social media strategy, media accompaniment for projects).",
  "literary_and_cross_cultural_analyst": "A user focused on literature, translation, and cross-cultural interpretation. Interested in comparative literature (e.g., Russian/Indonesian culture, adaptation of classics, Japanese/Eastern influences), textual theory, and analyzing cultural codes in society.",
  "history_and_ethnography_specialist": "A user with a strong interest in historical research, ethnography, and cultural anthropology. Prefers projects involving historical literature, folklore, archaeology, religious landscapes, and studying ethnic/social processes in historical contexts.",
  "creative_industries_and_arts_manager": "A user interested in the intersection of arts, creative industries, and institutional development. Prefers projects related to developing cultural centers, artistic galleries, film/theater projects, and managing creative community initiatives."
}

 16%|█▌        | 8/50 [03:22<17:25, 24.89s/it]

{
  "education_program_development_specialist": "A user highly focused on designing, organizing, and implementing educational programs, courses, and school structures (e.g., designing curricula, organizing schools, developing digital services for learning). Interested in pedagogy, educational technology, and program management.",
  "international_and_language_educator": "A user with a strong interest in multilingual education, foreign language teaching (French, German, Chinese), cross-cultural communication, and international student support/adaptation programs. Interested in linguistics and intercultural studies.",
  "educational_researcher_and_analysis": "A user interested in the analysis of educational trends, research methodologies (meta-analysis), the impact of technology (AI, digital tools) on learning, and policy issues within education (e.g., corruption risks, digitalization in Russia).",
  "mentorship_and_career_development_specialist": "A user focused on student support systems, mentorship, career guidance, competitive competitions, and developing professional skills for students (entrepreneurship, soft skills, university admissions). Interested in coaching and professional development."
}

 18%|█▊        | 9/50 [03:47<17:03, 24.96s/it]

{"historical_research_and_media_specialist": "A user deeply interested in comprehensive historical research, including archival work, bibliography, historiography, and the use of various media (film, literature, visual objects) to interpret the past. They value content creation and public engagement related to history.", "cultural_history_and_geography_expert": "A user focused on cultural history, geography, and the intersection of culture and politics across different regions (e.g., Middle East, Asia, Russia/Europe). They are interested in historical linguistics, art history, and the social memory of specific communities.", "russian_history_and_politics_analyst": "A user with a strong specialization in Russian and Soviet history, focusing on political evolution, elite studies, foreign relations, and social history within Russia and its global context. They are interested in high-level political and social analysis.", "historical_bibliography_and_curation_professional": "A user with strong organizational skills and an interest in the practical aspects of historical scholarship: cataloging, database creation, resource development (textbooks, guides), and managing historical collections/archives."}

 20%|██        | 10/50 [04:10<16:15, 24.38s/it]

{
  "media_strategist_and_producer": "A user highly interested in media strategy, content creation, production, and branding across various platforms (digital, film, podcasts). They likely enjoy cross-cultural studies and understanding media's role in social and political contexts.",
  "cultural_media_historian": "A user focused on the historical and semiotic aspects of media, particularly cinema, historical publications, and the evolution of visual codes (e.g., Soviet era, cultural memory). Interested in deep analysis of cultural artifacts.",
  "digital_and_social_media_expert": "A user specializing in the practical application of digital tools, social media management (SMM), content marketing, and the dynamics of online communities and digital communication.",
  "international_media_and_journalism_specialist": "A user interested in multilingual media, international cultural exchange (e.g., Iran, Asia, Africa, Korea), media in international relations, and journalistic practices across different geopolitical contexts."
}

 22%|██▏       | 11/50 [04:32<15:27, 23.79s/it]

{
  "legal_policy_and_regulation_expert": "A user deeply interested in the intersection of law, policy, and governance, focusing on international relations, public law, corruption, and legal frameworks for emerging technologies (like AI and digital diplomacy).",
  "legal_practice_and_prosecution_focused": "A user with a strong practical orientation, interested in litigation, legal clinics, specific areas like bankruptcy, intellectual property, and international arbitration, aiming for hands-on legal roles.",
  "legal_ethics_and_university_studies_enthusiast": "A user focused on the internal aspects of law, including university codes of conduct, legal education, student rights, and the ethical implications of technology and business practices.",
  "comparative_law_and_international_relations_specialist": "A user specializing in comparative law, focusing on cross-border legal issues, international trade/economics (e.g., EAEU, Iran/Russia relations), and international criminal/commercial law."
}

 24%|██▍       | 12/50 [04:58<15:31, 24.52s/it]

{
  "psychology_clinical_and_therapy_focus": "A user deeply interested in clinical psychology, therapy techniques (e.g., Transactional Analysis, Dasein-analysis), assessment tools (e.g., FUND-R, 3DM), and interventions (e.g., group therapy, intervision).",
  "psychology_developmental_and_educational": "A user focused on developmental psychology, student adaptation, educational psychology (curriculum development, pro-orientation), and school-based issues like bullying and mental well-being.",
  "psychology_social_and_cultural": "A user interested in broader social psychology, cultural factors (e.g., anti-corruption, cross-cultural competencies), interpersonal relationships (e.g., attachment, marital dynamics, peer support), and societal issues (e.g., stigma, social support).",
  "psychology_technology_and_measurement": "A user interested in the intersection of psychology and technology, including VR/AI in emotion measurement, developing psychological software (chatbots, online tests), and advanced statistical/neurocognitive methods."
}

 26%|██▌       | 13/50 [05:22<14:54, 24.17s/it]

{
  "geopolitics_strategic_analysis": "A user highly focused on high-level geopolitical strategy, international relations, and the analysis of major power dynamics (e.g., Russia, China, US, BRICS). Prefers deep dives into security issues, alliance structures, and long-term strategic planning.",
  "geopolitics_economic_monitoring": "A user interested in the intersection of geopolitics and economics, specifically focusing on macroeconomic trends, financial situations (like BRICS monitoring), trade relations, energy politics, and economic impact of geopolitical events.",
  "geopolitics_regional_studies": "A user specializing in specific geographic regions, such as East Asia, Central Asia, the Middle East, or Latin America, focusing on regional integration, specific bilateral relations, and sector-specific trends (e.g., Asian retail, Arctic policy).",
  "geopolitics_conflict_and_security": "A user focused on security studies, conflict analysis (e.g., Russo-Ukrainian conflict), military alliances, threat monitoring (OSINT), and the role of technology/energy in geopolitical competition."
}

 28%|██▊       | 14/50 [05:43<14:00, 23.35s/it]

{"literary_translator_and_cultural_studies": "A user deeply interested in literary translation across various languages (Japanese, Persian, Hindi, Arabic, French), comparative literature, and cross-cultural interpretation of texts.", "russian_literature_historian_and_critic": "A user focused on the history of literature (Turkish, medievalism, classical, modernism), literary theory, and analyzing specific literary movements (e.g., interwar period, specific poets).", "genre_and_text_analysis_specialist": "A user interested in specific literary devices, genres (poetry, prose, drama), textual analysis (meta-textuality, rhetoric), and the psychology of literary characters.", "cultural_and_media_studies_specialist": "A user focused on the intersection of literature and other fields: media studies, cultural studies, performing arts (theater, literary festivals), and the promotion of literary content in modern contexts."}

 30%|███       | 15/50 [06:04<13:13, 22.68s/it]

{"nlp_translator_and_localization_expert": "A user deeply interested in multilingual NLP, translation technologies (especially between complex language pairs like Arabic, Korean, Chinese), and large language models (LLMs) for text generation and summarization.", "nlp_ai_assistant_developer": "A user focused on building practical NLP applications, such as chatbots, learning assistants, automated grading systems, and personalized learning tools using AI/ML techniques.", "nlp_linguistics_and_corpus_builder": "A user specializing in the deep linguistic aspects of NLP, including morphological parsing, semantic analysis, corpus creation, and analyzing linguistic phenomena (e.g., temporal semantics, dialectology).", "nlp_multimodal_and_security_researcher": "A user interested in advanced, cutting-edge NLP research involving multimodal data (audio/video emotion detection), data security for dialogue systems, and application of AI in specialized domains (legal tech, mental health text analysis)."}

 32%|███▏      | 16/50 [06:22<12:01, 21.23s/it]

{"finance_macro_economist": "A user deeply interested in macroeconomic analysis, monetary policy, currency dynamics, and cross-border financial situations (e.g., BRICS, Russia/China/Brazil).", "investment_analyst_and_asset_manager": "A user focused on portfolio management, investment analysis (including alternative assets like crypto/ETF), corporate venture capital, and constructing indices.", "financial_regulator_and_compliance_expert": "A user concerned with legal aspects of finance, including bankruptcy, anti-money laundering (AML), regulatory frameworks, and compliance practices.", "fintech_and_consumer_behavior_researcher": "A user interested in the intersection of finance and technology, specifically digital channels, CRM strategies, financial applications, and consumer interaction in financial services."}

 34%|███▍      | 17/50 [06:44<11:44, 21.34s/it]

{"ai_education_startup_entrepreneur": "A user highly interested in developing AI-driven educational platforms, personalized learning systems, language learning tools (especially for less common languages like Korean, Arabic, Chinese), and building AI startups (MVP development). Focuses on productization and market viability.", "nlp_and_multimodal_analysis_specialist": "A user with a strong background in Natural Language Processing (NLP), speech processing, and multimodal AI. Interested in tasks like transcription, summarization, text generation for specific purposes, dialect analysis, and emotion detection across text/audio/video.", "business_ai_and_forecasting_analyst": "A user focused on applying Machine Learning and AI to solve complex business and financial problems. Interested in customer churn prediction, risk assessment, evaluating AI investment/ROI, and developing trading/scoring systems.", "advanced_ml_algorithms_and_systems": "A user with a deep interest in the theoretical and practical application of advanced ML/AI techniques, including graph-based search (BFS), generative models (LLMs), evolutionary algorithms, and algorithm comparison/optimization."}

 36%|███▌      | 18/50 [07:02<10:52, 20.41s/it]

{"political_science_geopolitics_expert": "A user deeply interested in international relations, geopolitics, and comparative politics, focusing on regional alliances, foreign policy analysis (especially Russia and its neighbors), and global systemic transformations.", "political_science_governance_and_corruption_analyst": "A user focused on public administration, governance, anti-corruption strategies, and the role of state institutions in modern political systems.", "political_science_elite_and_sociology": "A user interested in the sociology of politics, examining political elites, societal values, identity (ethnic/civic), and the intersection of social inequality with political structures.", "political_science_methodology_and_tech": "A user interested in the methodological aspects of political science, including the use of AI/algorithms in political analysis, qualitative/quantitative research tools, and specific language/discourse analysis."}

 38%|███▊      | 19/50 [07:21<10:22, 20.09s/it]

{
  "pedagogy_design_and_innovation": "A user deeply interested in pedagogical design, innovative teaching technologies (AI, digital tools), and the intersection of education and cognitive science (neurocognition, attention). Likely researches educational outcomes and methodologies.",
  "secondary_education_development": "A user focused on the structure, curriculum, and future of secondary education, including vocational guidance, social/economic sciences education, and preparing students for competitive environments (e.g., international competitions).",
  "language_and_foreign_language_pedagogy": "A specialist interested in teaching foreign languages (especially German and English), focusing on skill development (speaking, vocabulary), methods for teaching, and developing specific teaching materials.",
  "educational_leadership_and_mentoring": "A user interested in organizational aspects of education, mentorship, team dynamics in educational settings, and the development of educational ecosystems and support systems for students and parents."
}

 40%|████      | 20/50 [07:37<09:22, 18.76s/it]

{"project_manager_business_development": "A user focused on high-level project management, business strategy, and launching commercial projects (startups, omnichannel business models)", "education_and_program_development_manager": "A user interested in managing educational initiatives, developing curricula, organizing schools, and designing student programs (e.g., for foreign studies or specialized fields)", "non_profit_and_stakeholder_relations_specialist": "A user interested in the legal, organizational, and communicative aspects of NGOs, international collaborations, and managing public-facing projects", "media_and_events_coordinator": "A user with skills in media production, content management, event organization (conferences, meetups), and digital communication strategy"}

 42%|████▏     | 21/50 [07:55<08:58, 18.57s/it]

{
  "educational_tech_curriculum_design": "A user focused on designing, developing, and optimizing educational curricula, instructional materials, and learning platforms, with an interest in pedagogy and technology integration.",
  "ed_tech_ai_and_cognition_research": "A user interested in the intersection of educational technology, Artificial Intelligence (AI), cognitive science (neurocognition), and educational research (meta-analysis of student cognition).",
  "language_learning_tech_developer": "A user specializing in developing interactive tools, bots, and digital content for language learning, particularly foreign languages (Korean, English), and user experience (UX) research in EdTech.",
  "academic_support_and_administration": "A user focused on the administrative, organizational, and support aspects of education, including curriculum organization, quality assurance systems, faculty support tools, and academic communication."
}

 44%|████▍     | 22/50 [08:12<08:23, 18.00s/it]

{
  "media_strategist_and_content_creator": "A user focused on comprehensive media management, content creation (podcasts, social media), and PR/public relations for educational and cultural projects.",
  "cross_cultural_communication_specialist": "A user with a strong interest in intercultural communication, language (Persian, Chinese), and developing cross-cultural communication strategies.",
  "educational_media_marketer": "A user interested in using media and social media for marketing educational programs, promoting university initiatives, and managing student media.",
  "niche_community_builder": "A user focused on building and managing specific, niche online communities (Telegram channels, club media), focusing on specific topics like academic life or personal development."
}

 46%|████▌     | 23/50 [08:28<07:51, 17.48s/it]

{"management_strategy_and_consulting": "A user focused on high-level strategic management, corporate decision-making, competitive analysis, and consulting (e.g., SWOT analysis, strategic planning, industry competitiveness).", "organizational_development_and_governance": "A user interested in organizational structure, internal processes, governance, corruption prevention, and managing complex institutional/educational ecosystems.", "human_resources_and_leadership": "A user with a focus on talent management, leadership development (mentoring, training), conflict resolution, and personnel/staff motivation (e.g., assessing managers, incentive systems).", "international_business_and_global_strategy": "A user interested in international management, global startups, cross-cultural projects, and international partnership/ambassadorships."}

 48%|████▊     | 24/50 [08:47<07:46, 17.93s/it]

{
  "data_storage_and_startup_focus": "A user focused on developing practical software solutions, data infrastructure (e.g., data warehouses for specific domains like animal shelters), and launching business ventures (startups like marketplaces).",
  "edtech_and_ai_specialist": "A user deeply interested in educational technology (EdTech), particularly leveraging AI (AI tutors, personalized learning platforms) and developing interactive digital tools for students and professionals.",
  "multilingual_and_content_developer": "A user interested in localization, language technology (creating linguistic cards, chatbots for language learning), and cross-cultural communication projects (MENA guides, Korean language support).",
  "project_management_and_media_tech": "A user with skills in event management, media production/management (media centers, social networks), and developing specific tools for various sectors (e.g., massage industry ecosystem, legal tech platforms)."
}

 50%|█████     | 25/50 [09:04<07:17, 17.48s/it]

{
  "macroeconomic_geopolitical_analyst": "A user highly interested in macroeconomic trends, geopolitical risks, and global economic monitoring, likely using quantitative data analysis to inform strategic decisions.",
  "business_data_analyst_optimization": "A user focused on applying data analysis to solve specific business problems, particularly in e-commerce (marketplace optimization), financial risk management, and operational efficiency.",
  "social_and_qualitative_researcher": "A user interested in qualitative data analysis, social trends (e.g., happiness, public perception), policy analysis (labor practices, taxation), and interpreting complex narratives.",
  "big_data_and_osint_specialist": "A user with an interest in handling large datasets, utilizing OSINT tools for threat monitoring, and applying advanced analytical methods for decision support."
}

 52%|█████▏    | 26/50 [09:22<07:04, 17.68s/it]

{"ai_ethics_law_and_policy": "A user deeply interested in the legal, ethical, and geopolitical implications of AI, focusing on regulation, international relations, and policy (e.g., digital diplomacy, legal aspects of AI).", "ai_education_and_pedagogy": "A user focused on using AI for educational tools, curriculum development, and cognitive science research related to learning processes (e.g., meta-analysis of student cognition, AI tutors).", "ai_business_and_strategy": "A user interested in the practical, commercial, and strategic application of AI across various sectors, including HR, marketing, contact centers, and corporate investment in AI.", "ai_technical_and_development": "A user with a strong technical bent, interested in the development of specific AI tools, algorithms (generative AI vs. ML), and practical implementation (e.g., chatbot development, optimization tools)."}

 54%|█████▍    | 27/50 [09:39<06:47, 17.70s/it]

{
  "regional_studies_geopolitics_expert": "A user deeply interested in regional studies, international relations, geopolitics, and comparative socio-economic analysis across various global regions (Middle East, East Asia, Central Asia, Latin America).",
  "regional_policy_and_management_analyst": "A user focused on public administration, regional development, municipal management, economic differentiation within Russian regions, and policy impact analysis.",
  "international_relations_and_cultural_studies_enthusiast": "A user interested in the intersection of international relations, cultural studies (e.g., cinema, art history), and student/academic exchange programs across different geographical spheres.",
  "data_and_methodology_researcher": "A user focused on the methodological aspects of regional studies, data collection (including linguistic data), and developing research frameworks for complex geographical and socio-economic problems."
}

 56%|█████▌    | 28/50 [09:55<06:16, 17.14s/it]

{
  "strategic_business_consultant": "A user focused on high-level business strategy, corporate management decisions, market entry strategies (especially international/emerging markets), and competitive intelligence.",
  "ai_in_business_strategist": "A user interested in the strategic application of Artificial Intelligence (AI) in business operations, management, and organizational structure.",
  "international_market_expander": "A user highly interested in global market expansion, brand promotion across different geographic regions (e.g., Asia, Middle East, Africa), and cross-cultural marketing.",
  "new_venture_startup_developer": "A user focused on the foundational aspects of starting a business, including creating business plans, developing brand strategies (STMs), and identifying new product opportunities."
}

 58%|█████▊    | 29/50 [10:13<06:02, 17.26s/it]

{"cultural_media_strategist": "A user deeply interested in cultural studies, media management, and building online/physical cultural communities (e.g., running Telegram channels, organizing exhibitions).", " East_Asian_culture_expert": "A user with a strong focus on East Asian cultures (Japan, Korea, China, Vietnam), likely interested in theater, cinema, and cultural immersion.", "Middle_East_and_Cultural_Analysis": "A user interested in the art, history, and symbolism of the Middle East and the broader contemporary art scene.", "Cultural_and_Sociological_Theory": "A user interested in the intersection of culture, social capital, esoteric practices, and freedom of expression within a societal context (e.g., 'Эзотерические практики как форма социального и экономического капитала в России')."}

 60%|██████    | 30/50 [10:31<05:52, 17.63s/it]

{"digital_marketer_strategy_and_media": "A user focused on developing comprehensive digital marketing and media strategies for various entities (NGOs, educational programs, art institutions, tech startups). Highly skilled in content creation and multi-channel promotion.", "social_media_and_niche_marketing_expert": "A user specializing in social media management (Telegram, VK, etc.) for specific niches, such as historical culture, gaming studios, or specific product brands. Interested in audience engagement and platform-specific tactics.", "e_commerce_and_consumer_behavior_analyst": "A user interested in understanding consumer interaction in digital channels, particularly for financial services or analyzing customer acquisition strategies (SEO, digital channels).", "media_tech_and_digital_transformation_innovator": "A user with an interest in the intersection of media technology (Media-tech), digital transformation of content industries, and developing new business models for digital platforms."}

 62%|██████▏   | 31/50 [10:48<05:31, 17.42s/it]

{
  "media_strategy_and_publishing_manager": "A user focused on the business, editorial, and strategic aspects of media, including developing publications, managing media teams, and creating communication strategies for journals and media projects.",
  "cultural_and_social_journalist": "A user deeply interested in cultural studies, social issues, political history (especially Soviet/Eastern themes), and producing in-depth, long-form journalism and non-fiction content.",
  "sports_media_reporter": "A user specialized in sports journalism, focusing on covering competitive events (football, etc.), multimedia production (reports, broadcasts), and media coverage of student/team activities.",
  "digital_and_visual_media_creator": "A user interested in modern media formats, including video blogging, social media management, photojournalism analysis, and sensory studies/reviews."
}

 64%|██████▍   | 32/50 [11:05<05:12, 17.34s/it]

{
  "web_developer_fullstack_e_commerce": "A highly versatile developer skilled in full-stack development, comfortable with modern frameworks (ReactJS, FastAPI), and interested in building e-commerce or booking platforms.",
  "web_developer_application_and_data_systems": "A user focused on developing specific applications (student management, testing tools) and building robust database/information systems.",
  "web_developer_content_and_community_manager": "A user interested in content creation, managing online communities (social networks, journals), and developing niche informational websites.",
  "web_developer_niche_and_specialized_tools": "A developer interested in building specialized tools, such as Telegram bots, interactive maps, and platforms for specific communities or educational resources."
}

 66%|██████▌   | 33/50 [11:20<04:39, 16.46s/it]

{
  "event_manager_cultural_events": "A user highly skilled in event management, focusing on cultural, educational, and literary events. Interested in organizing festivals, conferences, and cultural showcases.",
  "sports_event_coordinator": "A user focused on organizing and supporting sports-related events, including competitions, team activities, and media coverage for student organizations.",
  "conference_and_forum_organizer": "A user specializing in the planning and execution of large-scale academic and international conferences, including scientific forums and specialized meetups.",
  "youth_program_developer": "A user interested in developing and implementing mass youth activities, civic education programs, and creating engaging platforms (like mobile apps) for events."
}

 68%|██████▊   | 34/50 [11:35<04:18, 16.15s/it]

{
  "literary_translator_specialist": "A user highly interested in literary translation, comparative literature (e.g., Shakespeare), and cross-cultural interpretation of texts.",
  "linguistics_and_multilingualism_researcher": "A user focused on applied linguistics, translation studies, multilingual media (e.g., Asian languages, Persian, Hindi), and sociolinguistics.",
  "legal_and_technical_translator": "A user interested in specialized translation fields, specifically legal texts and contemporary literature/media localization.",
  "language_acquisition_and_digital_content_focus": "A user interested in practical language teaching/acquisition (e.g., Hebrew for cross-cultural studies, basic courses) and translation in digital environments (subtitling, social media content)."
}

 70%|███████   | 35/50 [11:50<03:56, 15.74s/it]

{"geography_tourism_and_branding": "A user focused on geography applied to tourism, regional branding, and city promotion (e.g., designing longreads, developing guides, improving city image for specific audiences).", "geography_historical_and_source_study": "A user interested in historical geography, the use of geographical sources, and the study of ancient geography and cultural narratives.", "geography_regional_analysis_and_policy": "A user interested in political economy, regional planning, border analysis, economic rationalization of territories, and regional branding/territorial identity.", "geography_international_relations_and_cultural_exchange": "A user interested in geographical studies related to international relations, specific regions (MENA, Central Asia), and cross-cultural representation."}

 72%|███████▏  | 36/50 [12:05<03:37, 15.52s/it]

{"media_strategy_and_smm_expert": "A user highly interested in social media marketing, content creation, and media strategy, focusing on building and managing various platforms (Telegram, VK, video content).", "educational_media_producer": "A user focused on creating educational and informational media content, interested in developing materials for courses, and managing media channels related to specific academic fields (History, Media Management).", "creative_content_specialist": "A user with a strong creative inclination, interested in developing content for specific niches like music, art/fashion intellectual property, and documentary visual design.", "political_and_cultural_communicator": "A user focused on creating content related to history, politics, current events (Iran), and public discourse, interested in journalism and public communication."}

 74%|███████▍  | 37/50 [12:17<03:08, 14.53s/it]

{"public_relations_strategist": "A user deeply interested in public relations, media management, and communication strategy, focusing on educational institutions and scientific/business centers.", "social_media_media_manager": "A user with strong skills in social media marketing, content creation, and digital promotion, likely focused on outreach for academic or non-profit initiatives.", "educational_communications_expert": "A user specializing in developing communication strategies for educational programs, recruitment, and student organizations.", "PR_in_science_innovation": "A user interested in the intersection of Public Relations, science, and innovation, focusing on communicating research findings."}

 76%|███████▌  | 38/50 [12:33<02:56, 14.75s/it]

{"legal_expert_corruption_law": "A user deeply interested in corruption practices in bankruptcy procedures and the development of anti-corruption mechanisms, likely focusing on international legal approaches.", "international_arbitration_and_public_law_specialist": "A user focused on international public law, comparative law (especially Asian countries), and participation in international dispute resolution competitions (e.g., EAEU, arbitration).", "legal_education_and_ethics_developer": "A user interested in legal education design, university codes of ethics, developing legal glossaries, and engaging in student support/mentoring activities.", "criminal_procedure_and_practice_analyst": "A user focused on the practical aspects of criminal procedure, evidence transformation in the digital age, and specific areas like tax disputes and sports law."}

 78%|███████▊  | 39/50 [12:50<02:49, 15.43s/it]

{
  "social_science_researcher_policy_and_ethics": "A user focused on the intersection of social sciences, policy, and ethical considerations in research, with an interest in corruption risks and international approaches.",
  "social_science_outreach_and_education_specialist": "A user passionate about educational outreach, student clubs, developing educational programs (like 'School of Social and Economic Sciences'), and engaging with target audiences.",
  "social_science_methodology_and_analysis_expert": "A user highly interested in qualitative and quantitative data analysis, field research methods, political profiling, and exploring specific regional studies (e.g., Near East/Africa).",
  "social_science_digital_and_media_practitioner": "A user interested in the digital transformation of education, media освещение (media coverage), developing visual styles, and utilizing digital tools for sociological projects."
}

 80%|████████  | 40/50 [13:04<02:30, 15.08s/it]

{"market_strategy_consultant_global": "A user focused on high-level strategic consulting, market entry strategies across different countries, and analyzing global trends (e.g., Asia-Pacific, global tech startups).", "b2b_product_development_expert": "A user interested in developing digital products for B2B markets and identifying opportunities for new products within existing businesses.", "automotive_market_analyst": "A user specializing in detailed market analysis for specific industries, such as the automotive market (Russia), including logistics, competitive intelligence, and product development.", "fintech_and_crypto_analyst": "A user interested in the intersection of finance, cryptocurrency markets (AMM, liquidity), and their structural role in global markets."}

 82%|████████▏ | 41/50 [13:20<02:17, 15.31s/it]

{"strategic_business_development_expert": "A user highly focused on comprehensive business strategy, market entry, digital transformation, and creating market-ready business projects (omnichannel, new product launch). Interested in international business and corporate strategy.", "geopolitical_strategy_analyst": "A user with a strong interest in geopolitical strategy, national policy (e.g., China), and understanding strategic hurdles in emerging markets (Nigeria). Prefers high-level analysis and strategic consulting.", "innovation_strategy_manager": "A user focused on the strategic management of innovation, particularly within large or multinational enterprises. Interested in how to integrate AI/digitalization into corporate strategy.", "market_and_product_strategist": "A user interested in developing detailed marketing strategies for specific products (e.g., Endokey, Chery) and understanding competitive landscapes and consumer trends."}

 84%|████████▍ | 42/50 [13:36<02:05, 15.67s/it]

{"geopolitical_and_socioeconomic_analyst": "A user interested in comparative analysis across diverse geopolitical, socio-economic, and cultural contexts (e.g., Russia vs. others, different regions like Asia, Africa, Central Asia)", "international_relations_and_policy_expert": "A user focused on comparative analysis of governmental policies, international relations, legal frameworks, and public opinion across different nations (e.g., EU policy, media influence, capital movement control)", "cross_cultural_narrative_researcher": "A user interested in qualitative and quantitative methods for comparing national narratives, media representations, and cultural phenomena across different countries", "business_and_media_strategy_analyst": "A user focused on comparative analysis of business models, corporate governance, media industry evolution, and specific market strategies (e.g., sports clubs, media companies, investment climates)"}

 86%|████████▌ | 43/50 [13:51<01:48, 15.45s/it]

{"social_media_marketing_strategist": "A user focused on developing comprehensive content and communication strategies for various projects, brands, and educational programs across multiple platforms (Telegram, VK, Instagram).", "community_manager_and_brand_builder": "A user interested in building and managing online communities (e.g., BuddyUP) and promoting specific brands (fashion, perfume, music) through social media.", "educational_content_specialist": "A user concentrating on leveraging social media to promote academic programs, language learning, and educational content (e.g., literature, finance, language courses).", "digital_media_editor_and_SEO_expert": "A user with skills in content editing, media institution promotion, and technical optimization (SEO for YouTube) for specific target markets."}

 88%|████████▊ | 44/50 [14:07<01:34, 15.72s/it]

{
  "macro_economist_russia_specialist": "A user deeply interested in Russian macroeconomics, focusing on specific issues like inflation, monetary policy (especially unconventional policies), fiscal policy, and the dynamics of the ruble.",
  "international_macro_analyst": "A user focused on comparative macroeconomics, interested in analyzing the economic situations and policies of BRICS countries, and cross-country investment activity.",
  "econometric_data_scientist": "A user who prefers quantitative analysis, focusing on building automated databases for macroeconomic statistics and performing complex quantitative comparisons of economic narratives.",
  "monetary_policy_theorist": "A user with a strong theoretical interest in central banking, specifically studying the mechanics and effectiveness of monetary policy tools, interest rate settings, and transmission channels."
}

 90%|█████████ | 45/50 [14:23<01:18, 15.62s/it]

{"language_teaching_methodology_expert": "A user deeply interested in the methodologies of multilingual education, curriculum development, and pedagogical practices in various languages (German, Chinese, Korean, Arabic, English).", "applied_language_teacher_specialist": "A user focused on practical application, such as being a teacher/tutor, developing specific teaching materials, and working with diverse student populations (including university settings and foreign learners).", "linguistics_and_curriculum_designer": "A user interested in the theoretical and organizational aspects of language teaching, including developing textbooks, linguistic analysis (dialects), and the structure of language programs.", "technology_in_language_pedagogy_advocate": "A user interested in the intersection of modern technology and language learning, specifically the use of video materials and innovative teaching tools."}

 92%|█████████▏| 46/50 [14:40<01:03, 15.98s/it]

{"cultural_heritage_database_expert": "A user deeply interested in digital humanities, archival science, and the creation/management of large, specialized databases focused on cultural history (especially artistic/historical figures and sites).", "information_systems_developer_academic": "A user focused on the practical development and implementation of Information Systems (IS) solutions within an academic/university setting, emphasizing student support, administrative tools, and IT infrastructure management.", "digital_navigation_and_geospatial_data_specialist": "A user interested in creating user-facing digital products, such as interactive maps and specialized navigation tools (e.g., for tourists or legal/student services), likely incorporating GIS or web development.", "strategic_data_and_forecasting_analyst": "A user interested in high-level information management, strategic data bases (expert networks, societal initiatives), and applying digital tools to support decision-making processes."}

 94%|█████████▍| 47/50 [14:55<00:47, 15.75s/it]

{"film_studies_sociology_philosophy": "A user deeply interested in the intersection of film, social memory, philosophy, and historical contexts, likely pursuing academic research in cultural studies or film theory.", "film_studies_language_and_culture": "A user focused on the linguistic and cultural aspects of cinema, particularly comparative studies involving foreign films (Turkish, Korean, Chinese) and translation/dubbing.", "film_studies_media_and_theory": "A user interested in the broader theoretical and interdisciplinary aspects of cinema, including cross-media projects, visual aesthetics, and the semiotics of film.", "film_studies_historical_curator": "A user interested in practical application of film studies, such as curating film clubs, historical consultancy, and specific national cinemas."}

 96%|█████████▌| 48/50 [15:10<00:31, 15.60s/it]

{"social_media_strategist_education": "A user highly focused on social media marketing within the educational sector, specializing in promoting master's programs, university labs, and specialized courses.", "content_creator_and_niche_marketing": "A user interested in developing diverse content strategies across various social media platforms (Telegram, VK) for niche communities, academic programs, and specific topics (e.g., linguistics, media management).", "brand_and_community_manager": "A user skilled in managing social media presence for brands, clubs, and community groups, focusing on engagement and building community around specific projects.", "SMM_for_career_and_recruitment": "A user interested in using social media for professional purposes, such as recruiting students, finding job opportunities, and marketing HR-related programs."}

 98%|█████████▊| 49/50 [15:28<00:16, 16.29s/it]

{
  "social_worker_community_organizer": "A user focused on community building, youth engagement, and developing social and cultural groups (e.g., 'STEPS COMMUNITY', group self-help). Interested in organizing events and community initiatives.",
  "social_worker_specialist_in_vulnerable_populations": "A user deeply interested in supporting specific vulnerable groups, particularly those affected by HIV, children from specific regions (Asia/Middle East), and individuals with dependencies. Focused on direct aid and advocacy.",
  "social_worker_policy_and_legal_advocate": "A user with an interest in the intersection of social work and policy/law, including legal aid, combating stigma (media representation), and developing youth policy/education programs.",
  "social_worker_researcher_and_methodologist": "A user focused on the theoretical and methodological aspects of social work, including developing research methodologies for family systems and analyzing professional dilemmas within the social sphere."
}

100%|██████████| 50/50 [15:39<00:00, 18.79s/it]

{"higher_education_international_relations": "A user focused on international higher education, student mobility, and international conferences.", "higher_education_program_management": "A user interested in developing and promoting university programs (Master's, Bachelor's) and academic strategy.", "academic_support_and_mentoring": "A user interested in student support, academic advising, mentorship, and creating effective learning environments.", "university_promotion_and_outreach": "A user focused on public relations, social media promotion of research labs, and institutional outreach."}

In [29]:
len(answers)

200

In [30]:
answers

{'international_relations_geopolitics_expert': 'A user deeply interested in complex geopolitical dynamics, focusing on BRICS, Eurasia, China-Russia relations, energy politics, and regional conflicts (Middle East, Central Asia). Prefers research into strategic interests and policy mechanisms.',
 'international_relations_regional_studies_enthusiast': "A user focused on regional studies, particularly East Asia (Japan, Korea, China, Vietnam) and South Asia. Interested in cultural exchange, specific bilateral relationships, and regional blocs (like the 'Trio' of Northeast Asia).",
 'international_relations_law_and_security_analyst': 'A user interested in the legal and security aspects of international relations, including information security, dispute resolution mechanisms (EAEU), and the role of international law in digital diplomacy.',
 'international_relations_student_and_ambassador': 'A student or young professional actively involved in student clubs, networking, media management (social media, podcasts), and visa/adaptation support for international students.',
 'sociology_culture_and_identity_expert': 'A user deeply interested in cultural studies, identity formation, social memory, and the intersection of culture, politics, and media. Prefers qualitative research, ethnography, and critical analysis of cultural phenomena.',
 'intercultural_communication_and_global_studies': 'A user focused on cross-cultural communication, international relations, and comparative studies (e.g., Russia/Mexico, various Asian codes). Interested in global trends, political sociology, and comparative cultural practices.',
 'social_and_political_theory_researcher': 'A user leaning towards theoretical sociology, focusing on large-scale societal structures, political elites, social inequality, and the impact of technology (AI) on society. Seeks high-level theoretical understanding.',
 'social_and_youth_issues_specialist': 'A user interested in contemporary social issues, including youth agency, mental health (e.g., HIV, bullying), social entrepreneurship, and digital culture (memes). Interested in applied sociology and intervention strategies.',
 'macroeconomic_and_geopolitical_analyst': 'A user highly interested in global economics, geopolitics, international trade, and macroeconomic trends. Prefers quantitative analysis of large-scale data (e.g., GlobBaro HSE, BRICS, sanctions impact).',
 'russian_economic_policy_expert': 'A user focused on the internal economic dynamics of Russia, including monetary policy (inflation, exchange rates, central banking), fiscal policy, regional economics, and the impact of geopolitical turbulence on the national economy.',
 'international_business_and_trade_specialist': 'A user interested in comparative economics, international trade relations (Asia, BRICS, ASEAN), foreign investment, and the business environment in different countries (especially emerging markets).',
 'applied_economics_and_fintech_practitioner': 'A user interested in practical business applications of economics, including pricing strategy, market analysis (e.g., marketplaces like Ozon), financial innovation, and behavioral economics.',
 'linguistics_translator_and_corpus_builder': 'A user deeply engaged in language translation, corpus creation, and textual analysis across diverse languages (Japanese, Arabic, Hebrew, Hindi, etc.). Interested in both classical texts and modern media, with a strong focus on linguistic documentation and methodology.',
 'cross_cultural_communicator_specialist': 'A user focused on inter-cultural communication, cross-cultural studies (Russia/Mexico, general), and developing intercultural competence materials. Interested in sociolinguistics and practical communication skills.',
 'language_curriculum_developer': 'A user focused on educational linguistics, curriculum design, and developing teaching materials for various languages (Japanese, Chinese, Korean, French, English). Interested in pedagogical methods and language teaching.',
 'computational_linguistics_and_NLP_enthusiast': 'A user interested in applying computational methods (LLMs, parsers, automatic classification) to linguistic data, morphology, semantics, and dialectology. Interested in the intersection of NLP and language research.',
 'education_tech_developer': 'A user highly interested in educational technology, software engineering for learning platforms, AI integration in education, and developing various types of assistants (chatbots, learning systems).',
 'full_stack_mobile_developer': 'A user focusing on building cross-platform mobile applications (Flutter, React Native, Kotlin) and backend systems (Java, Rust) for various purposes (finance, fitness, social networks).',
 'data_and_system_architect': 'A user interested in large-scale data management, database development (including specific domains like economics or legal), system architecture for complex processes (e.g., oil/gas supervision), and data quality monitoring (LLMOps).',
 'media_and_community_builder': 'A user interested in content creation, media platforms (Telegram bots, online journals), community building (BuddyUP), and developing interactive media solutions (VR, maps, educational content creation).',
 'digital_marketing_strategist': 'A user highly focused on comprehensive digital marketing strategy, encompassing SMM, content creation, brand positioning, and cross-platform promotion across various sectors (education, consumer goods, tech).',
 'brand_management_and_rebranding_expert': 'A user with a strong interest in brand strategy, rebranding, product development (FMCG, fashion, beverages), and leveraging personality/AI in marketing communications.',
 'media_and_PR_specialist': 'A user focused on media relations, PR campaigns, event promotion, media management for institutions, and strategic communication for cultural or sports entities.',
 'market_research_and_consumer_insights': 'A user interested in market analysis, consumer behavior research (especially in niche areas like food, finance, and specific demographics), and identifying market opportunities for new products/services.',
 'cultural_studies_media_strategist': 'A user deeply interested in cultural studies, media production, and digital presence. Prefers projects involving website development, media promotion, content strategy for cultural programs, and analyzing the impact of media on cultural spheres (e.g., social media strategy, media accompaniment for projects).',
 'literary_and_cross_cultural_analyst': 'A user focused on literature, translation, and cross-cultural interpretation. Interested in comparative literature (e.g., Russian/Indonesian culture, adaptation of classics, Japanese/Eastern influences), textual theory, and analyzing cultural codes in society.',
 'history_and_ethnography_specialist': 'A user with a strong interest in historical research, ethnography, and cultural anthropology. Prefers projects involving historical literature, folklore, archaeology, religious landscapes, and studying ethnic/social processes in historical contexts.',
 'creative_industries_and_arts_manager': 'A user interested in the intersection of arts, creative industries, and institutional development. Prefers projects related to developing cultural centers, artistic galleries, film/theater projects, and managing creative community initiatives.',
 'education_program_development_specialist': 'A user highly focused on designing, organizing, and implementing educational programs, courses, and school structures (e.g., designing curricula, organizing schools, developing digital services for learning). Interested in pedagogy, educational technology, and program management.',
 'international_and_language_educator': 'A user with a strong interest in multilingual education, foreign language teaching (French, German, Chinese), cross-cultural communication, and international student support/adaptation programs. Interested in linguistics and intercultural studies.',
 'educational_researcher_and_analysis': 'A user interested in the analysis of educational trends, research methodologies (meta-analysis), the impact of technology (AI, digital tools) on learning, and policy issues within education (e.g., corruption risks, digitalization in Russia).',
 'mentorship_and_career_development_specialist': 'A user focused on student support systems, mentorship, career guidance, competitive competitions, and developing professional skills for students (entrepreneurship, soft skills, university admissions). Interested in coaching and professional development.',
 'historical_research_and_media_specialist': 'A user deeply interested in comprehensive historical research, including archival work, bibliography, historiography, and the use of various media (film, literature, visual objects) to interpret the past. They value content creation and public engagement related to history.',
 'cultural_history_and_geography_expert': 'A user focused on cultural history, geography, and the intersection of culture and politics across different regions (e.g., Middle East, Asia, Russia/Europe). They are interested in historical linguistics, art history, and the social memory of specific communities.',
 'russian_history_and_politics_analyst': 'A user with a strong specialization in Russian and Soviet history, focusing on political evolution, elite studies, foreign relations, and social history within Russia and its global context. They are interested in high-level political and social analysis.',
 'historical_bibliography_and_curation_professional': 'A user with strong organizational skills and an interest in the practical aspects of historical scholarship: cataloging, database creation, resource development (textbooks, guides), and managing historical collections/archives.',
 'media_strategist_and_producer': "A user highly interested in media strategy, content creation, production, and branding across various platforms (digital, film, podcasts). They likely enjoy cross-cultural studies and understanding media's role in social and political contexts.",
 'cultural_media_historian': 'A user focused on the historical and semiotic aspects of media, particularly cinema, historical publications, and the evolution of visual codes (e.g., Soviet era, cultural memory). Interested in deep analysis of cultural artifacts.',
 'digital_and_social_media_expert': 'A user specializing in the practical application of digital tools, social media management (SMM), content marketing, and the dynamics of online communities and digital communication.',
 'international_media_and_journalism_specialist': 'A user interested in multilingual media, international cultural exchange (e.g., Iran, Asia, Africa, Korea), media in international relations, and journalistic practices across different geopolitical contexts.',
 'legal_policy_and_regulation_expert': 'A user deeply interested in the intersection of law, policy, and governance, focusing on international relations, public law, corruption, and legal frameworks for emerging technologies (like AI and digital diplomacy).',
 'legal_practice_and_prosecution_focused': 'A user with a strong practical orientation, interested in litigation, legal clinics, specific areas like bankruptcy, intellectual property, and international arbitration, aiming for hands-on legal roles.',
 'legal_ethics_and_university_studies_enthusiast': 'A user focused on the internal aspects of law, including university codes of conduct, legal education, student rights, and the ethical implications of technology and business practices.',
 'comparative_law_and_international_relations_specialist': 'A user specializing in comparative law, focusing on cross-border legal issues, international trade/economics (e.g., EAEU, Iran/Russia relations), and international criminal/commercial law.',
 'psychology_clinical_and_therapy_focus': 'A user deeply interested in clinical psychology, therapy techniques (e.g., Transactional Analysis, Dasein-analysis), assessment tools (e.g., FUND-R, 3DM), and interventions (e.g., group therapy, intervision).',
 'psychology_developmental_and_educational': 'A user focused on developmental psychology, student adaptation, educational psychology (curriculum development, pro-orientation), and school-based issues like bullying and mental well-being.',
 'psychology_social_and_cultural': 'A user interested in broader social psychology, cultural factors (e.g., anti-corruption, cross-cultural competencies), interpersonal relationships (e.g., attachment, marital dynamics, peer support), and societal issues (e.g., stigma, social support).',
 'psychology_technology_and_measurement': 'A user interested in the intersection of psychology and technology, including VR/AI in emotion measurement, developing psychological software (chatbots, online tests), and advanced statistical/neurocognitive methods.',
 'geopolitics_strategic_analysis': 'A user highly focused on high-level geopolitical strategy, international relations, and the analysis of major power dynamics (e.g., Russia, China, US, BRICS). Prefers deep dives into security issues, alliance structures, and long-term strategic planning.',
 'geopolitics_economic_monitoring': 'A user interested in the intersection of geopolitics and economics, specifically focusing on macroeconomic trends, financial situations (like BRICS monitoring), trade relations, energy politics, and economic impact of geopolitical events.',
 'geopolitics_regional_studies': 'A user specializing in specific geographic regions, such as East Asia, Central Asia, the Middle East, or Latin America, focusing on regional integration, specific bilateral relations, and sector-specific trends (e.g., Asian retail, Arctic policy).',
 'geopolitics_conflict_and_security': 'A user focused on security studies, conflict analysis (e.g., Russo-Ukrainian conflict), military alliances, threat monitoring (OSINT), and the role of technology/energy in geopolitical competition.',
 'literary_translator_and_cultural_studies': 'A user deeply interested in literary translation across various languages (Japanese, Persian, Hindi, Arabic, French), comparative literature, and cross-cultural interpretation of texts.',
 'russian_literature_historian_and_critic': 'A user focused on the history of literature (Turkish, medievalism, classical, modernism), literary theory, and analyzing specific literary movements (e.g., interwar period, specific poets).',
 'genre_and_text_analysis_specialist': 'A user interested in specific literary devices, genres (poetry, prose, drama), textual analysis (meta-textuality, rhetoric), and the psychology of literary characters.',
 'cultural_and_media_studies_specialist': 'A user focused on the intersection of literature and other fields: media studies, cultural studies, performing arts (theater, literary festivals), and the promotion of literary content in modern contexts.',
 'nlp_translator_and_localization_expert': 'A user deeply interested in multilingual NLP, translation technologies (especially between complex language pairs like Arabic, Korean, Chinese), and large language models (LLMs) for text generation and summarization.',
 'nlp_ai_assistant_developer': 'A user focused on building practical NLP applications, such as chatbots, learning assistants, automated grading systems, and personalized learning tools using AI/ML techniques.',
 'nlp_linguistics_and_corpus_builder': 'A user specializing in the deep linguistic aspects of NLP, including morphological parsing, semantic analysis, corpus creation, and analyzing linguistic phenomena (e.g., temporal semantics, dialectology).',
 'nlp_multimodal_and_security_researcher': 'A user interested in advanced, cutting-edge NLP research involving multimodal data (audio/video emotion detection), data security for dialogue systems, and application of AI in specialized domains (legal tech, mental health text analysis).',
 'finance_macro_economist': 'A user deeply interested in macroeconomic analysis, monetary policy, currency dynamics, and cross-border financial situations (e.g., BRICS, Russia/China/Brazil).',
 'investment_analyst_and_asset_manager': 'A user focused on portfolio management, investment analysis (including alternative assets like crypto/ETF), corporate venture capital, and constructing indices.',
 'financial_regulator_and_compliance_expert': 'A user concerned with legal aspects of finance, including bankruptcy, anti-money laundering (AML), regulatory frameworks, and compliance practices.',
 'fintech_and_consumer_behavior_researcher': 'A user interested in the intersection of finance and technology, specifically digital channels, CRM strategies, financial applications, and consumer interaction in financial services.',
 'ai_education_startup_entrepreneur': 'A user highly interested in developing AI-driven educational platforms, personalized learning systems, language learning tools (especially for less common languages like Korean, Arabic, Chinese), and building AI startups (MVP development). Focuses on productization and market viability.',
 'nlp_and_multimodal_analysis_specialist': 'A user with a strong background in Natural Language Processing (NLP), speech processing, and multimodal AI. Interested in tasks like transcription, summarization, text generation for specific purposes, dialect analysis, and emotion detection across text/audio/video.',
 'business_ai_and_forecasting_analyst': 'A user focused on applying Machine Learning and AI to solve complex business and financial problems. Interested in customer churn prediction, risk assessment, evaluating AI investment/ROI, and developing trading/scoring systems.',
 'advanced_ml_algorithms_and_systems': 'A user with a deep interest in the theoretical and practical application of advanced ML/AI techniques, including graph-based search (BFS), generative models (LLMs), evolutionary algorithms, and algorithm comparison/optimization.',
 'political_science_geopolitics_expert': 'A user deeply interested in international relations, geopolitics, and comparative politics, focusing on regional alliances, foreign policy analysis (especially Russia and its neighbors), and global systemic transformations.',
 'political_science_governance_and_corruption_analyst': 'A user focused on public administration, governance, anti-corruption strategies, and the role of state institutions in modern political systems.',
 'political_science_elite_and_sociology': 'A user interested in the sociology of politics, examining political elites, societal values, identity (ethnic/civic), and the intersection of social inequality with political structures.',
 'political_science_methodology_and_tech': 'A user interested in the methodological aspects of political science, including the use of AI/algorithms in political analysis, qualitative/quantitative research tools, and specific language/discourse analysis.',
 'pedagogy_design_and_innovation': 'A user deeply interested in pedagogical design, innovative teaching technologies (AI, digital tools), and the intersection of education and cognitive science (neurocognition, attention). Likely researches educational outcomes and methodologies.',
 'secondary_education_development': 'A user focused on the structure, curriculum, and future of secondary education, including vocational guidance, social/economic sciences education, and preparing students for competitive environments (e.g., international competitions).',
 'language_and_foreign_language_pedagogy': 'A specialist interested in teaching foreign languages (especially German and English), focusing on skill development (speaking, vocabulary), methods for teaching, and developing specific teaching materials.',
 'educational_leadership_and_mentoring': 'A user interested in organizational aspects of education, mentorship, team dynamics in educational settings, and the development of educational ecosystems and support systems for students and parents.',

In [31]:
with open("artificial_profiles.json", "w") as f:
    json.dump(answers, f)