In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
from dotenv import load_dotenv

In [3]:
load_dotenv()

True

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel("data.xlsx", header=0)

In [6]:
df.head()

,title_rus,title_eng,goals,tasks,annotation,description,expectations,product_result,result_criterias,social_effect,commercial_effect
0,Исследование приоритетов и механизмов реализац...,Study of Priorities and Mechanisms for Impleme...,Целью проекта является эмпирическая проверка г...,1) Анализ повестки международных доноров\n2) А...,Работа международных фондов (доноров) должна п...,"Согласно определению международных фондов, про...",Аналитический отчет по избранным странам.\n\nС...,NaN,NaN,NaN,NaN
1,Антрополе - научно-популярный видео-подкаст о ...,Anthropole is a Popular Science Video Podcast ...,Выпустить и популяризовать 27 видео-подкастов ...,Снять и смонтировать подкасты;\nРазработать ст...,"\tАнтрополе - научно-популярный проект, в рамк...","Социальное знание близко и интересно обществу,...","Студенты получат опыт монтажа, продвижения и к...",Регулярный видео-подкаст (+экспедиционные филь...,Опубликованы 27 видео-подкастов о необычных со...,Популяризация социального знания должна привес...,Планируется в течение года выйти на окупаемост...
2,"Разработка, создание и ведение сайта, посвящен...","Design, Development and Implementation of a We...","Для того, чтобы получить более полное представ...",Подготовка технического задания для разработчи...,Художественное образование и творчество художн...,Тема обучения арабских художников в художестве...,"Навыки создания сайта (полный цикл, от подгото...","Создание сайта, посвященного истории арабских ...",Выполнение заданий руководителя проекта,Укрепление международных связей с художниками ...,NaN
3,Перевод с английского языка коллективной моног...,Translation from English of the collective mon...,Результатом проекта станет качественный перево...,Результатом проекта станет качественный перево...,"Коллективная монография, авторы которой являют...","Коллективная монография, авторы которой являют...",Участники проекта приобретут новые знания в об...,Результатом проекта станет качественный перево...,Критериями достижения результата будет возможн...,NaN,NaN
4,Сеть военно-политических союзов в Евразии: баз...,Network of Military in Eurasia: a Database,Целью проекта является создание базы данных со...,1.\tОпределение методики включения союзов в ба...,Проект посвящен изучению сети военно-политичес...,Проект посвящен анализу истории существования ...,1.\tОбучение навыкам сбора и анализа данных 2....,База данных союзов 1815-2024 в Евразии.,Создание базы данных как минимум тысячи диадны...,NaN,NaN

In [7]:
df = df.fillna("")

In [8]:
df.head()

,title_rus,title_eng,goals,tasks,annotation,description,expectations,product_result,result_criterias,social_effect,commercial_effect
0,Исследование приоритетов и механизмов реализац...,Study of Priorities and Mechanisms for Impleme...,Целью проекта является эмпирическая проверка г...,1) Анализ повестки международных доноров\n2) А...,Работа международных фондов (доноров) должна п...,"Согласно определению международных фондов, про...",Аналитический отчет по избранным странам.\n\nС...,,,,
1,Антрополе - научно-популярный видео-подкаст о ...,Anthropole is a Popular Science Video Podcast ...,Выпустить и популяризовать 27 видео-подкастов ...,Снять и смонтировать подкасты;\nРазработать ст...,"\tАнтрополе - научно-популярный проект, в рамк...","Социальное знание близко и интересно обществу,...","Студенты получат опыт монтажа, продвижения и к...",Регулярный видео-подкаст (+экспедиционные филь...,Опубликованы 27 видео-подкастов о необычных со...,Популяризация социального знания должна привес...,Планируется в течение года выйти на окупаемост...
2,"Разработка, создание и ведение сайта, посвящен...","Design, Development and Implementation of a We...","Для того, чтобы получить более полное представ...",Подготовка технического задания для разработчи...,Художественное образование и творчество художн...,Тема обучения арабских художников в художестве...,"Навыки создания сайта (полный цикл, от подгото...","Создание сайта, посвященного истории арабских ...",Выполнение заданий руководителя проекта,Укрепление международных связей с художниками ...,
3,Перевод с английского языка коллективной моног...,Translation from English of the collective mon...,Результатом проекта станет качественный перево...,Результатом проекта станет качественный перево...,"Коллективная монография, авторы которой являют...","Коллективная монография, авторы которой являют...",Участники проекта приобретут новые знания в об...,Результатом проекта станет качественный перево...,Критериями достижения результата будет возможн...,,
4,Сеть военно-политических союзов в Евразии: баз...,Network of Military in Eurasia: a Database,Целью проекта является создание базы данных со...,1.\tОпределение методики включения союзов в ба...,Проект посвящен изучению сети военно-политичес...,Проект посвящен анализу истории существования ...,1.\tОбучение навыкам сбора и анализа данных 2....,База данных союзов 1815-2024 в Евразии.,Создание базы данных как минимум тысячи диадны...,,

In [9]:
df.shape

(1258, 11)

In [10]:
df = df.drop_duplicates(inplace=False).reset_index(drop=True)

In [11]:
df.shape

(1250, 11)

In [12]:
df = df.dropna(axis=0)

In [13]:
df.shape

(1250, 11)

In [14]:
def clean_text(text):

    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.replace("\t", " ")

    text = text.lower()

    return text

In [15]:
for col in df.columns:
    df[col] = df.apply(lambda x: clean_text(x[col]), axis=1)

In [16]:
df.head()

,title_rus,title_eng,goals,tasks,annotation,description,expectations,product_result,result_criterias,social_effect,commercial_effect
0,исследование приоритетов и механизмов реализац...,study of priorities and mechanisms for impleme...,целью проекта является эмпирическая проверка г...,1) анализ повестки международных доноров 2) ан...,работа международных фондов (доноров) должна п...,"согласно определению международных фондов, про...",аналитический отчет по избранным странам. сфо...,,,,
1,антрополе - научно-популярный видео-подкаст о ...,anthropole is a popular science video podcast ...,выпустить и популяризовать 27 видео-подкастов ...,снять и смонтировать подкасты; разработать стр...,"антрополе - научно-популярный проект, в рамка...","социальное знание близко и интересно обществу,...","студенты получат опыт монтажа, продвижения и к...",регулярный видео-подкаст (+экспедиционные филь...,опубликованы 27 видео-подкастов о необычных со...,популяризация социального знания должна привес...,планируется в течение года выйти на окупаемост...
2,"разработка, создание и ведение сайта, посвящен...","design, development and implementation of a we...","для того, чтобы получить более полное представ...",подготовка технического задания для разработчи...,художественное образование и творчество художн...,тема обучения арабских художников в художестве...,"навыки создания сайта (полный цикл, от подгото...","создание сайта, посвященного истории арабских ...",выполнение заданий руководителя проекта,укрепление международных связей с художниками ...,
3,перевод с английского языка коллективной моног...,translation from english of the collective mon...,результатом проекта станет качественный перево...,результатом проекта станет качественный перево...,"коллективная монография, авторы которой являют...","коллективная монография, авторы которой являют...",участники проекта приобретут новые знания в об...,результатом проекта станет качественный перево...,критериями достижения результата будет возможн...,,
4,сеть военно-политических союзов в евразии: баз...,network of military in eurasia: a database,целью проекта является создание базы данных со...,1. определение методики включения союзов в баз...,проект посвящен изучению сети военно-политичес...,проект посвящен анализу истории существования ...,1. обучение навыкам сбора и анализа данных 2. ...,база данных союзов 1815-2024 в евразии.,создание базы данных как минимум тысячи диадны...,,

In [17]:
df.tail()

,title_rus,title_eng,goals,tasks,annotation,description,expectations,product_result,result_criterias,social_effect,commercial_effect
1245,влияние мер контроля за движением капитала на ...,the impact of capital controls on the investme...,,,,,,,,,
1246,"создание страницы (лендинга) проектов пул ""раз...",creation of a landing page for projects of the...,основная цель: создать эффективный digital-инс...,разработать информационную архитектуру и прото...,проект направлен на разработку и запуск одност...,проектно-учебная лаборатория «развитие универс...,навыки анализа потребностей заказчика. опыт ра...,"рабочий, опубликованный в интернете лендинг.",функциональные: все разделы лендинга работают ...,,"повышение конверсии запросов в контракты, форм..."
1247,разработка стратегической и контентно-коммуник...,development of a strategic and content-based c...,1. разработать целостную стратегию присутствия...,для маркетолога (стратега): - провести аудит t...,проект предполагает разработку системной комму...,экосистема «вулканариум–ойкумена» объединяет н...,участники: - овладеют навыком комплексного ауд...,стратегический документ (дорожная карта на 3–6...,- наличие полноценного стратегического докумен...,- поддержка просветительской миссии музея «вул...,- повышение эффективности продвижения услуг (э...
1248,актив центра развития карьеры - профориентацио...,active club of the career development center -...,сформировать у студентов питерской вышки базов...,1. разработать и реализовать мероприятия центр...,актив центра развития карьеры — это проектная ...,актуальность проекта «актив центра развития ка...,1. навыки самостоятельной работы и принятия от...,,,,
1249,обзор методологии в области регионоведения. эт...,area studies methodology overview. data collec...,создать базу данных,апдейтнуть,данный этап заключается в поиске и сортировке ...,на текущий момент существует разрозненные пред...,вклад в формирование базы данных о методология...,,,,

# Transformers

In [18]:
from sentence_transformers import SentenceTransformer

In [19]:
model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 13582.86it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [20]:
import json

In [21]:
corpus = []

for row in df.to_dict(orient="records"):
    corpus.append(json.dumps(row, ensure_ascii=False))

In [22]:
embeddings = model.encode(corpus, normalize_embeddings=True)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
def semantic_search_verbose(query: str, top_k: int = 5):
    q_emb = model.encode([query], normalize_embeddings=True)
    sims = cosine_similarity(q_emb, embeddings).ravel()
    top_idx = np.argsort(-sims)[:top_k]
    print(top_idx)
    return pd.DataFrame(data=zip(df.iloc[top_idx]["title_rus"].to_list(), sims[top_idx], ["transformer"] * top_k), columns=["title", "score", "algo"])

In [25]:
semantic_search_verbose(query=json.dumps(["макроэкономика", "ключевая ставка", "процентная ставка", "центральный банк", "денежно-кредитная политика"], ensure_ascii=False))

[1079 1107 1068 1071 1078]

                                               title     score         algo
0  динамика валютного курса рубля: факторы и возд...  0.634648  transformer
1  оценка роли выпуска субфедеральных облигаций в...  0.627383  transformer
2  нестандартная монетарная политика: особенности...  0.621463  transformer
3  монетарная политика в условиях нулевых и отриц...  0.604422  transformer
4       теория и практика валютной политики в россии  0.574485  transformer

In [26]:
def semantic_search(query: str, top_k: int = 5):
    q_emb = model.encode([query], normalize_embeddings=True)
    sims = cosine_similarity(q_emb, embeddings).ravel()
    top_idx = np.argsort(-sims)[:top_k]
    return df.iloc[top_idx]["title_rus"].to_list()

In [29]:
semantic_search(query=json.dumps(["процентная ставка", "центральный банк", "денежно-кредитная политика"], ensure_ascii=False))

['оценка роли выпуска субфедеральных облигаций в формировании финансовой устойчивости и экономического роста регионов',
 'нестандартная монетарная политика: особенности, инструменты и результаты проведения',
 'монетарная политика в условиях нулевых и отрицательных процентных ставок',
 'динамика валютного курса рубля: факторы и воздействие на ключевые макроэкономические переменные',
 'влияние и эффективность смягчения регулирования центральным банком: данные китайских и американских банков.']

In [33]:
semantic_search_verbose(query=json.dumps(["компьютерное зрение", "программирование", "компьютерные науки"], ensure_ascii=False))

[ 572   54 1029  968  169]

                                               title     score         algo
0  металлосводка: управляемая и масштабируемая си...  0.651500  transformer
1  научно-популярный проект "мультивселенная ученых"  0.641554  transformer
2             система электронного проведения заявок  0.629482  transformer
3  ассистент преподавателя по дисциплине "введени...  0.627626  transformer
4  разработка визуального стиля для лаборатории с...  0.621580  transformer

In [34]:
semantic_search(query=json.dumps(["компьютерное зрение", "программирование", "компьютерные науки"], ensure_ascii=False))

['металлосводка: управляемая и масштабируемая система мониторинга цифрового следа предприятия (на примере пао “северсталь”)',
 'научно-популярный проект "мультивселенная ученых"',
 'система электронного проведения заявок',
 'ассистент преподавателя по дисциплине "введение в количественный анализ текста"',
 'разработка визуального стиля для лаборатории сравнительных социальных исследований им. р. ф. инглхарта']

In [36]:
df.iloc[54]["description"]

'проект направлен на привлечение школьников и студентов к выбору научной карьеры,  повышение интереса аудитории к актуальным исследованиям в сфере нейронаук путем создания привлекательного образа ученых в виде  персонажей комиксов и распространения их через социальные сети'

# LLM-as-Judge

In [ ]:
query = "движение капитала"

messages = []

for rec in semantic_search(query):
    messages.append(
        (
            {"role": "system", "content": "You are a helpful assistant, which evaluates quality of student projects recommendations"},
            {"role": "user", "content": f"Evaluate, how does a recommended project title fits initial query. Here is initial query: '{query}'. Here is recommended project title: '{rec}'. Give an explanation in Russian"},
        ),
    )

In [ ]:
messages[1]

In [ ]:
from transformers import AutoProcessor, AutoModelForCausalLM

In [ ]:
MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

In [ ]:
processor = AutoProcessor.from_pretrained(MODEL_ID)

In [ ]:
llm = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype="auto",
    device_map="auto",
)

In [ ]:
text = processor.apply_chat_template(
    messages, 
    tokenize=False, 
    add_generation_prompt=True, 
    enable_thinking=False,
    padding_side="left",
)

In [ ]:
inputs = processor(text=text, return_tensors="pt", padding=True, truncation=True).to(llm.device)

In [ ]:
input_len = inputs["input_ids"].shape[-1]

In [ ]:
outputs = llm.generate(**inputs, max_new_tokens=512)

In [ ]:
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, outputs)
]

In [ ]:
processor.batch_decode(generated_ids, skip_special_tokens=True)