In [1]:
import os
import re
import json
import pickle

import tqdm
import numpy as np
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv

In [2]:
load_dotenv()

True

In [3]:
SEED = 23
TEMPERATURE = 0.1

In [4]:
MODEL = "google/gemini-2.5-flash"

In [5]:
output_dir_name = MODEL.split("/")[1]

In [6]:
df = pd.read_excel("data_clean.xlsx", header=0)

In [7]:
df.head(10)

,title_rus,title_eng,annotation,description
0,Исследование приоритетов и механизмов реализац...,Study of Priorities and Mechanisms for Impleme...,Работа международных фондов (доноров) должна п...,"Согласно определению международных фондов, про..."
1,Антрополе - научно-популярный видео-подкаст о ...,Anthropole is a Popular Science Video Podcast ...,"\tАнтрополе - научно-популярный проект, в рамк...","Социальное знание близко и интересно обществу,..."
2,"Разработка, создание и ведение сайта, посвящен...","Design, Development and Implementation of a We...",Художественное образование и творчество художн...,Тема обучения арабских художников в художестве...
3,Перевод с английского языка коллективной моног...,Translation from English of the collective mon...,"Коллективная монография, авторы которой являют...","Коллективная монография, авторы которой являют..."
4,Сеть военно-политических союзов в Евразии: баз...,Network of Military in Eurasia: a Database,Проект посвящен изучению сети военно-политичес...,Проект посвящен анализу истории существования ...
5,Дизайн учебных материалов (презентаций),Instructional Materials Design (PPT Presentati...,Участникам проекта предлагается оформить две у...,Необходимо оформить две учебные презентации в ...
6,ОРЗ Изучении практик многоязычного обучения в ...,Studying the Practices of Polylingual Educatio...,Участие в нашем проекте будет интересен для те...,Преподавание родного языка и родной литературы...
7,Привязанность к месту и психосоциальное здоров...,Place attachment and psychosocial health: a me...,Привязанность к месту (place attachment) — это...,Привязанность к месту (place attachment) — сра...
8,Подготовка управленческих решений на корпорати...,Preparation of Managerial Decisions at the Co...,Для осуществления управленческих функций необх...,Сложности подготовки управленческих решений на...
9,"Дизайн лонгрида ""Корея в Москве и Санкт-Петерб...","Design of a Longread ""Korea in Moscow and St. ...",Подготовка привлекательного визуального отобра...,Сейчас завершается финальная часть проекта по ...

In [ ]:
with open(f"{output_dir_name}/artificial_profiles.json", "r") as f:
    profiles = json.load(f)

In [ ]:
with open(f"gemma-4-E2B-it/titles_with_tags_dict.pkl", "rb") as f:
    titles_with_tags_dict = pickle.load(f)

In [ ]:
data = []

for title in titles_with_tags_dict:
    for tag in titles_with_tags_dict[title]:
        data.append((title, tag))

titles_df = pd.DataFrame(data=data, columns=["title", "tag"])

In [11]:
titles_df.head()

                                               title                      tag
0  Исследование приоритетов и механизмов реализац...  international_relations
1  Исследование приоритетов и механизмов реализац...        political_science
2  Исследование приоритетов и механизмов реализац...                economics
3  Исследование приоритетов и механизмов реализац...      development_studies
4  Исследование приоритетов и механизмов реализац...                    BRICS

In [12]:
client = OpenAI(
    api_key=os.environ.get("KODIK_API_KEY"),
    base_url="https://api.kodikrouter.ru/v1",
)

In [13]:
results = {}

In [14]:
for profile, description in tqdm.tqdm(list(profiles.items())):

    SYSTEM_PROMPT = f"""
    You are a {profile}.
    Yours bio: '{description['bio']}'
    Yours tags: '{description['tags']}'
    Evaluate, how much you would like proposed student project based on its title in russian and tags. Rate it on a scale [1, 2, 3, 4, 5], where the higher the better.
    Return stricly JSON.
    For example.
    """
    SYSTEM_PROMPT += """
    Input.
    ```json
    {'title': 'Исследование методов решения задачи линейной регрессии', 'tags': ['machine_learning', 'algorithms']}
    ```
    """
    SYSTEM_PROMPT += """
    Output.
    ```json
    {'score': 5}
    ```
    """

    messages = [
        (
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": json.dumps(
                    {
                        "title": row[1]["title"],
                        "tags": titles_with_tags[row[1]["title"]],
                    },
                    ensure_ascii=False,
                ),
            },
        )
        for row in titles_df[titles_df["tag"].isin(description["tags"])].iterrows()
    ]

    titles = [msg[1]["content"] for msg in messages]

    print(f"{profile}: {len(titles)} titles to evaluate")

    scores = {}

    for title, message in zip(titles, messages):

        try:

            response = client.chat.completions.create(
                model=MODEL,
                messages=message,
                seed=SEED,
                temperature=TEMPERATURE,
            )

            content = response.choices[0].message.content

            json_match = re.search(r"```json\s*(.*?)\s*```", content, re.DOTALL)
            if json_match:
                json_str = json_match.group(1)
            else:
                json_str = content

            answer = json.loads(json_str)

        except Exception:

            answer = {"score": None}

        try:

            score = answer.get("score", None)
            score = int(score)
            scores[title] = score

        except (TypeError, ValueError):

            print(f"{profile}: something wrong went with title {title}")

    values = list(scores.values())
    if len(values):
        median = np.median(values)
    else:
        median = np.nan

    print(f"{profile}: {len(values)}, {median}")

    results[profile] = scores

  0%|          | 0/31 [00:00<?, ?it/s]

cultural_studies_enthusiast: 27 titles to evaluate

  3%|▎         | 1/31 [00:22<11:19, 22.66s/it]

cultural_studies_enthusiast: 27, 5.0
educational_content_developer: 160 titles to evaluate

  6%|▋         | 2/31 [02:42<44:10, 91.41s/it]

educational_content_developer: 157, 4.0
media_content_creator: 18 titles to evaluate

 10%|▉         | 3/31 [02:54<25:53, 55.48s/it]

media_content_creator: 18, 5.0
geopolitical_analyst_brics_middle_east: 130 titles to evaluate

 13%|█▎        | 4/31 [04:33<32:37, 72.51s/it]

geopolitical_analyst_brics_middle_east: 124, 4.0
cultural_exchange_coordinator: 55 titles to evaluate

 16%|█▌        | 5/31 [05:22<27:42, 63.92s/it]

cultural_exchange_coordinator: 55, 4.0
sociology_and_cultural_studies_enthusiast: 138 titles to evaluate

 19%|█▉        | 6/31 [07:17<33:56, 81.45s/it]

sociology_and_cultural_studies_enthusiast: 128, 5.0
geopolitical_analyst: 133 titles to evaluate

 23%|██▎       | 7/31 [09:08<36:26, 91.12s/it]

geopolitical_analyst: 123, 5.0
data_management_specialist: 30 titles to evaluate

 26%|██▌       | 8/31 [09:31<26:34, 69.32s/it]

data_management_specialist: 29, 4.0
marketing_and_media_strategist: 100 titles to evaluate

 29%|██▉       | 9/31 [10:49<26:26, 72.10s/it]

marketing_and_media_strategist: 89, 5.0
global_economic_analyst: 125 titles to evaluate

 32%|███▏      | 10/31 [12:37<29:05, 83.10s/it]

global_economic_analyst: 105, 5.0
linguistics_and_cultural_studies_enthusiast: 115 titles to evaluate

 35%|███▌      | 11/31 [14:34<31:12, 93.62s/it]

linguistics_and_cultural_studies_enthusiast: 100, 5.0
software_developer_for_educational_platforms: 222 titles to evaluate

 39%|███▊      | 12/31 [17:43<38:48, 122.58s/it]

software_developer_for_educational_platforms: 207, 4.0
business_strategist: 109 titles to evaluate

 42%|████▏     | 13/31 [19:07<33:16, 110.93s/it]

business_strategist: 97, 4.0
east_asia_cultural_specialist: 36 titles to evaluate

 45%|████▌     | 14/31 [19:35<24:17, 85.74s/it]

east_asia_cultural_specialist: 36, 5.0
legal_innovation_and_education_enthusiast: 16 titles to evaluate

 48%|████▊     | 15/31 [19:47<16:55, 63.46s/it]

legal_innovation_and_education_enthusiast: 16, 5.0
geopolitical_analyst_global_economy: 101 titles to evaluate

 52%|█████▏    | 16/31 [21:19<18:02, 72.20s/it]

geopolitical_analyst_global_economy: 97, 4.0
psychology_researcher_mental_health_and_wellbeing: 69 titles to evaluate

 55%|█████▍    | 17/31 [22:18<15:56, 68.34s/it]

psychology_researcher_mental_health_and_wellbeing: 64, 5.0
project_manager_and_event_organizer: 142 titles to evaluate

 58%|█████▊    | 18/31 [24:27<18:42, 86.31s/it]

project_manager_and_event_organizer: 118, 5.0
event_organizer_and_community_builder: 126 titles to evaluate

 61%|██████▏   | 19/31 [26:13<18:27, 92.30s/it]

event_organizer_and_community_builder: 107, 5.0
financial_analyst_macro_and_micro: 131 titles to evaluate

 65%|██████▍   | 20/31 [27:58<17:37, 96.11s/it]

financial_analyst_macro_and_micro: 110, 4.0
cultural_cinema_enthusiast: 23 titles to evaluate

 68%|██████▊   | 21/31 [28:16<12:06, 72.63s/it]

cultural_cinema_enthusiast: 23, 5.0
ai_in_education_and_law_enthusiast: 247 titles to evaluate

 71%|███████   | 22/31 [31:44<16:59, 113.25s/it]

ai_in_education_and_law_enthusiast: 226, 4.0
art_and_culture_enthusiast: 22 titles to evaluate

 74%|███████▍  | 23/31 [32:00<11:14, 84.26s/it]

art_and_culture_enthusiast: 22, 4.0
linguistic_ai_developer: 139 titles to evaluate

 77%|███████▋  | 24/31 [33:51<10:44, 92.10s/it]

linguistic_ai_developer: 132, 4.0
web_platform_developer: 35 titles to evaluate

 81%|████████  | 25/31 [34:21<07:20, 73.45s/it]

web_platform_developer: 34, 5.0
ai_in_education_innovator: 183 titles to evaluate

 84%|████████▍ | 26/31 [37:20<08:46, 105.37s/it]

ai_in_education_innovator: 177, 3.0
media_and_communications_specialist: 175 titles to evaluate

 87%|████████▋ | 27/31 [39:35<07:35, 113.96s/it]

media_and_communications_specialist: 143, 5.0
african_and_middle_eastern_studies_researcher: 16 titles to evaluate

 90%|█████████ | 28/31 [39:56<04:18, 86.30s/it]

african_and_middle_eastern_studies_researcher: 16, 4.5
student_life_coordinator: 73 titles to evaluate

 94%|█████████▎| 29/31 [41:02<02:40, 80.28s/it]

student_life_coordinator: 67, 5.0
urban_cultural_researcher: 33 titles to evaluate

 97%|█████████▋| 30/31 [41:27<01:03, 63.68s/it]

urban_cultural_researcher: 31, 5.0
mobile_app_developer: 24 titles to evaluate

100%|██████████| 31/31 [41:51<00:00, 81.02s/it]

mobile_app_developer: 19, 5.0

In [15]:
with open(f"{output_dir_name}/artificial_profiles_scores.pkl", "wb") as f:
    pickle.dump(results, f)